import type { FormData } from '@/types/modul';
import { resetModulAutoFillFields } from './constants';

/**
 * Helper bersama untuk AI Auto-fill (seksi 2, 3, 5, 6 + pemanfaatan digital).
 * Dipakai oleh Mode Cepat (Index.tsx) dan Workspace (WorkspaceMeetingEditor.tsx)
 * agar semantik merge/reset konsisten di semua jalur.
 */

/**
 * Cek apakah FormData berisi isian auto-fill (hasil AI atau manual) yang
 * terkait dengan materi saat ini.
 */
export function hasAutoFillContent(fd: FormData): boolean {
  const hasAny = (obj?: object | null) =>
    !!obj && Object.values(obj).some((v) => typeof v === 'string' && v.trim() !== '');
  return (
    [fd.aspekPengetahuanAwal, fd.aspekMinat, fd.aspekLatarBelakang, fd.aspekKebutuhanBelajar, fd.kaitanKehidupan]
      .some((v) => !!v && v.trim() !== '') ||
    hasAny(fd.materiPengetahuan) ||
    hasAny(fd.lintasDisiplinIlmu) ||
    hasAny(fd.kemitraanPembelajaran) ||
    hasAny(fd.lingkunganPembelajaranDetail) ||
    hasAny(fd.pemanfaatanDigitalDetail) ||
    (fd.nilaiKarakter?.length ?? 0) > 0 ||
    (fd.dimensiProfilLulusan?.length ?? 0) > 0 ||
    (fd.topikPancaCinta?.length ?? 0) > 0 ||
    !!fd.materiIntegrasiKBC
  );
}

/**
 * Terapkan field `auto_generated` dari respons AI ke FormData.
 * Semantik merge: nilai dari AI HANYA menimpa isian lama jika AI benar-benar
 * mengembalikan nilai (string non-kosong / array non-kosong). Field yang tidak
 * dikembalikan AI mempertahankan nilai sebelumnya — jadi isian lama tidak lagi
 * "mengunci" hasil auto-fill berikutnya.
 *
 * @param prev      FormData sebelumnya
 * @param autoGen   objek `auto_generated` dari respons generate-content
 *                  (menerima juga respons dibungkus { auto_generated: {...} })
 */
export function applyAutoGeneratedFields(prev: FormData, autoGen: unknown): FormData {
  const ag = ((autoGen as Record<string, unknown> | null | undefined)?.auto_generated ?? autoGen) as
    | Record<string, unknown>
    | null
    | undefined;
  if (!ag) return prev;

  const pickStr = (...candidates: unknown[]): string | undefined => {
    for (const c of candidates) {
      if (typeof c === 'string' && c.trim() !== '') return c;
    }
    return undefined;
  };
  // dpl_deskripsi / panca_cinta_deskripsi di FormData bertipe Record<kode, deskripsi>.
  // AI bisa mengembalikan Record per-kode (prompt baru) atau string umum (prompt lama) —
  // string dinormalisasi ke Record agar aman dikonsumsi DocumentPreview.
  const pickDesc = (
    keys: string[] | undefined,
    ...candidates: unknown[]
  ): Record<string, string> | undefined => {
    for (const c of candidates) {
      if (c && typeof c === 'object' && !Array.isArray(c) && Object.keys(c).length > 0) {
        return c as Record<string, string>;
      }
    }
    if (keys && keys.length > 0) {
      for (const c of candidates) {
        if (typeof c === 'string' && c.trim() !== '') {
          return Object.fromEntries(keys.map((k) => [k, c]));
        }
      }
    }
    return undefined;
  };
  const pickArr = (val: unknown): string[] | undefined =>
    Array.isArray(val) && val.length > 0 ? (val as string[]) : undefined;
  const nested = (obj: unknown, ...keys: string[]): string | undefined =>
    pickStr(...keys.map((k) => (obj as Record<string, unknown> | null | undefined)?.[k]));

  const im = ag.identifikasi_murid;
  const mp = ag.materi_pengetahuan;
  const ld = ag.lintas_disiplin;
  const km = ag.kemitraan;
  const lg = ag.lingkungan;
  const pd = ag.pemanfaatan_digital;

  return {
    ...prev,
    aspekPengetahuanAwal: nested(im, 'aspek_pengetahuan_awal', 'pengetahuanAwal') ?? prev.aspekPengetahuanAwal ?? '',
    aspekMinat: nested(im, 'aspek_minat', 'minat') ?? prev.aspekMinat ?? '',
    aspekLatarBelakang: nested(im, 'aspek_latar_belakang', 'latarBelakang') ?? prev.aspekLatarBelakang ?? '',
    aspekKebutuhanBelajar: nested(im, 'aspek_kebutuhan_belajar', 'kebutuhanBelajar') ?? prev.aspekKebutuhanBelajar ?? '',
    materiPengetahuan: {
      faktual: nested(mp, 'faktual') ?? prev.materiPengetahuan?.faktual ?? '',
      konseptual: nested(mp, 'konseptual') ?? prev.materiPengetahuan?.konseptual ?? '',
      prosedural: nested(mp, 'prosedural') ?? prev.materiPengetahuan?.prosedural ?? '',
      metakognitif: nested(mp, 'metakognitif') ?? prev.materiPengetahuan?.metakognitif ?? '',
    },
    kaitanKehidupan: nested(ag, 'kaitan_kehidupan', 'kaitanKehidupan') ?? prev.kaitanKehidupan ?? '',
    dimensiProfilLulusan: pickArr(ag.dimensi_profil_lulusan ?? ag.dimensiProfilLulusan) ?? prev.dimensiProfilLulusan,
    dimensiProfilLulusanDeskripsi: pickDesc(
      pickArr(ag.dimensi_profil_lulusan ?? ag.dimensiProfilLulusan) ?? prev.dimensiProfilLulusan,
      ag.dpl_deskripsi,
      ag.dimensiProfilLulusanDeskripsi
    ) ?? prev.dimensiProfilLulusanDeskripsi,
    nilaiKarakter: pickArr(ag.nilai_karakter ?? ag.nilaiKarakter) ?? prev.nilaiKarakter,
    lintasDisiplinIlmu: {
      ppkn: nested(ld, 'ppkn') ?? prev.lintasDisiplinIlmu?.ppkn ?? '',
      ips: nested(ld, 'ips') ?? prev.lintasDisiplinIlmu?.ips ?? '',
      matematika: nested(ld, 'matematika') ?? prev.lintasDisiplinIlmu?.matematika ?? '',
      bahasaIndonesia: nested(ld, 'bahasa_indonesia', 'bahasaIndonesia') ?? prev.lintasDisiplinIlmu?.bahasaIndonesia ?? '',
      seniBudaya: nested(ld, 'seni_budaya', 'seniBudaya') ?? prev.lintasDisiplinIlmu?.seniBudaya ?? '',
      prakarya: nested(ld, 'prakarya') ?? prev.lintasDisiplinIlmu?.prakarya ?? '',
      penjaskes: nested(ld, 'penjaskes') ?? prev.lintasDisiplinIlmu?.penjaskes ?? '',
    },
    kemitraanPembelajaran: {
      guruBidangStudiLain: nested(km, 'guru_bidang_studi_lain', 'guruBidangStudiLain') ?? prev.kemitraanPembelajaran?.guruBidangStudiLain ?? '',
      orangTua: nested(km, 'orang_tua', 'orangTua') ?? prev.kemitraanPembelajaran?.orangTua ?? '',
      tokohMasyarakat: nested(km, 'tokoh_masyarakat', 'tokohMasyarakat') ?? prev.kemitraanPembelajaran?.tokohMasyarakat ?? '',
      instansiTerkait: nested(km, 'instansi_terkait', 'instansiTerkait') ?? prev.kemitraanPembelajaran?.instansiTerkait ?? '',
      duniaUsaha: nested(km, 'dunia_usaha', 'duniaUsaha') ?? prev.kemitraanPembelajaran?.duniaUsaha ?? '',
      perguruanTinggiLSM: nested(km, 'perguruan_tinggi_lsm', 'perguruanTinggiLSM') ?? prev.kemitraanPembelajaran?.perguruanTinggiLSM ?? '',
      mgmpKomunitasBelajar: nested(km, 'mgmp_komunitas_belajar', 'mgmpKomunitasBelajar') ?? prev.kemitraanPembelajaran?.mgmpKomunitasBelajar ?? '',
    },
    lingkunganPembelajaranDetail: {
      ruangFisik: nested(lg, 'ruang_fisik', 'ruangFisik') ?? prev.lingkunganPembelajaranDetail?.ruangFisik ?? '',
      ruangVirtual: nested(lg, 'ruang_virtual', 'ruangVirtual') ?? prev.lingkunganPembelajaranDetail?.ruangVirtual ?? '',
      budayaBelajar: nested(lg, 'budaya_belajar', 'budayaBelajar') ?? prev.lingkunganPembelajaranDetail?.budayaBelajar ?? '',
    },
    pemanfaatanDigitalDetail: {
      perencanaan: nested(pd, 'perencanaan') ?? prev.pemanfaatanDigitalDetail?.perencanaan ?? '',
      pelaksanaan: nested(pd, 'pelaksanaan') ?? prev.pemanfaatanDigitalDetail?.pelaksanaan ?? '',
      asesmen: nested(pd, 'asesmen') ?? prev.pemanfaatanDigitalDetail?.asesmen ?? '',
    },
    topikPancaCinta: pickArr(ag.topik_panca_cinta ?? ag.topikPancaCinta) ?? prev.topikPancaCinta,
    topikPancaCintaDeskripsi: pickDesc(
      pickArr(ag.topik_panca_cinta ?? ag.topikPancaCinta) ?? prev.topikPancaCinta,
      ag.panca_cinta_deskripsi,
      ag.topikPancaCintaDeskripsi
    ) ?? prev.topikPancaCintaDeskripsi,
    materiIntegrasiKBC: nested(ag, 'materi_integrasi_kbc', 'materiIntegrasiKBC') ?? prev.materiIntegrasiKBC ?? '',
  };
}

/**
 * Handler perubahan input form dengan reset auto-fill otomatis:
 * saat user MENGGANTI materi yang sudah terisi, seluruh isian auto-fill lama
 * dibersihkan (resetModulAutoFillFields) agar AI mengisi ulang secara
 * kontekstual untuk materi baru — bukan menampilkan nilai modul sebelumnya.
 * Mengisi materi yang masih kosong (first fill) TIDAK melakukan reset,
 * agar isian manual sebelum memilih materi tidak hilang.
 */
export function applyMateriChange(prev: FormData, materi: string): FormData {
  if (prev.materi && materi !== prev.materi && hasAutoFillContent(prev)) {
    return { ...resetModulAutoFillFields(prev), materi };
  }
  return { ...prev, materi };
}
