import { describe, it, expect } from 'vitest';
import { applyAutoGeneratedFields, applyMateriChange, hasAutoFillContent } from './autofill';
import { DEFAULT_FORM_DATA } from './constants';
import type { FormData } from '@/types/modul';

const baseForm = (): FormData => ({
  ...DEFAULT_FORM_DATA,
  materiPengetahuan: { ...DEFAULT_FORM_DATA.materiPengetahuan },
  lintasDisiplinIlmu: { ...DEFAULT_FORM_DATA.lintasDisiplinIlmu },
  kemitraanPembelajaran: { ...DEFAULT_FORM_DATA.kemitraanPembelajaran },
  lingkunganPembelajaranDetail: { ...DEFAULT_FORM_DATA.lingkunganPembelajaranDetail },
  pemanfaatanDigitalDetail: { ...DEFAULT_FORM_DATA.pemanfaatanDigitalDetail },
  nilaiKarakter: [],
  dimensiProfilLulusan: [],
  topikPancaCinta: [],
});

describe('hasAutoFillContent', () => {
  it('false untuk form default', () => {
    expect(hasAutoFillContent(baseForm())).toBe(false);
  });

  it('true jika ada satu saja isian auto-fill', () => {
    expect(hasAutoFillContent({ ...baseForm(), aspekMinat: 'suka game' })).toBe(true);
    expect(hasAutoFillContent({ ...baseForm(), pemanfaatanDigitalDetail: { perencanaan: 'Canva', pelaksanaan: '', asesmen: '' } })).toBe(true);
    expect(hasAutoFillContent({ ...baseForm(), nilaiKarakter: ['Religius'] })).toBe(true);
  });

  it('false untuk string kosong/whitespace', () => {
    expect(hasAutoFillContent({ ...baseForm(), aspekMinat: '   ' })).toBe(false);
  });
});

describe('applyAutoGeneratedFields', () => {
  it('menimpa isian lama dengan hasil AI (bukan sebaliknya)', () => {
    const prev: FormData = { ...baseForm(), aspekMinat: 'LAMA', kaitanKehidupan: 'LAMA' };
    const next = applyAutoGeneratedFields(prev, {
      identifikasi_murid: { aspek_minat: 'BARU kontekstual' },
      kaitan_kehidupan: 'BARU kontekstual',
    });
    expect(next.aspekMinat).toBe('BARU kontekstual');
    expect(next.kaitanKehidupan).toBe('BARU kontekstual');
  });

  it('mempertahankan nilai lama bila AI mengembalikan string kosong / key hilang', () => {
    const prev: FormData = {
      ...baseForm(),
      aspekMinat: 'LAMA',
      lintasDisiplinIlmu: { ...baseForm().lintasDisiplinIlmu, ips: 'peta' },
    };
    const next = applyAutoGeneratedFields(prev, {
      identifikasi_murid: { aspek_minat: '', aspek_pengetahuan_awal: '  ' },
      lintas_disiplin: { ips: '' },
    });
    expect(next.aspekMinat).toBe('LAMA');
    expect(next.lintasDisiplinIlmu.ips).toBe('peta');
  });

  it('menerima respons terbungkus { auto_generated: {...} } maupun langsung', () => {
    const wrapped = applyAutoGeneratedFields(baseForm(), { auto_generated: { kaitan_kehidupan: 'A' } });
    const direct = applyAutoGeneratedFields(baseForm(), { kaitan_kehidupan: 'A' });
    expect(wrapped.kaitanKehidupan).toBe('A');
    expect(direct.kaitanKehidupan).toBe('A');
  });

  it('menerima key camelCase (respons suggest-desain) untuk identifikasi murid', () => {
    const next = applyAutoGeneratedFields(baseForm(), {
      identifikasi_murid: { pengetahuanAwal: 'dari suggest', minat: 'musik' },
    });
    expect(next.aspekPengetahuanAwal).toBe('dari suggest');
    expect(next.aspekMinat).toBe('musik');
  });

  it('dpl_deskripsi: Record per-kode DPL diteruskan, string dinormalisasi ke Record', () => {
    const asObj = applyAutoGeneratedFields(baseForm(), {
      dimensi_profil_lulusan: ['DPL 3', 'DPL 5'],
      dpl_deskripsi: { 'DPL 3': 'penalaran kritis untuk teks prosedur', 'DPL 5': 'kolaborasi' },
    });
    expect(asObj.dimensiProfilLulusanDeskripsi).toEqual({ 'DPL 3': 'penalaran kritis untuk teks prosedur', 'DPL 5': 'kolaborasi' });

    // Respons prompt lama berupa string umum → dipetakan ke DPL terpilih
    const asStr = applyAutoGeneratedFields(baseForm(), {
      dimensi_profil_lulusan: ['DPL 3'],
      dpl_deskripsi: 'deskripsi umum',
    });
    expect(asStr.dimensiProfilLulusanDeskripsi).toEqual({ 'DPL 3': 'deskripsi umum' });
  });

  it('array kosong dari AI tidak menghapus pilihan lama', () => {
    const prev: FormData = { ...baseForm(), dimensiProfilLulusan: ['DPL 3'], nilaiKarakter: ['Religius'] };
    const next = applyAutoGeneratedFields(prev, { dimensi_profil_lulusan: [], nilai_karakter: [] });
    expect(next.dimensiProfilLulusan).toEqual(['DPL 3']);
    expect(next.nilaiKarakter).toEqual(['Religius']);
  });

  it('tidak mengubah identitas guru / materi / TP', () => {
    const prev: FormData = { ...baseForm(), namaPenyusun: 'Pak H', materi: 'Teks Prosedur', tujuanPembelajaran: 'TP1' };
    const next = applyAutoGeneratedFields(prev, { kaitan_kehidupan: 'resep masakan' });
    expect(next.namaPenyusun).toBe('Pak H');
    expect(next.materi).toBe('Teks Prosedur');
    expect(next.tujuanPembelajaran).toBe('TP1');
  });
});

describe('applyMateriChange', () => {
  it('mengganti materi → isian auto-fill direset agar AI mengisi ulang', () => {
    const prev: FormData = {
      ...baseForm(),
      materi: 'Teks Prosedur',
      aspekMinat: 'hasil modul lama',
      nilaiKarakter: ['Religius'],
      pemanfaatanDigitalDetail: { perencanaan: 'Canva lama', pelaksanaan: '', asesmen: '' },
    };
    const next = applyMateriChange(prev, 'Puisi');
    expect(next.materi).toBe('Puisi');
    expect(next.aspekMinat).toBe('');
    expect(next.nilaiKarakter).toEqual([]);
    expect(next.pemanfaatanDigitalDetail.perencanaan).toBe('');
  });

  it('isian materi pertama kali (dari kosong) tidak me-reset apapun', () => {
    const prev: FormData = { ...baseForm(), materi: '', aspekMinat: 'manual' };
    const next = applyMateriChange(prev, 'Puisi');
    expect(next.materi).toBe('Puisi');
    expect(next.aspekMinat).toBe('manual');
  });

  it('materi sama (edit kecil / re-render) tidak me-reset', () => {
    const prev: FormData = { ...baseForm(), materi: 'Puisi', aspekMinat: 'hasil AI' };
    const next = applyMateriChange(prev, 'Puisi');
    expect(next.aspekMinat).toBe('hasil AI');
  });

  it('identitas guru & TP tetap dipertahankan saat reset', () => {
    const prev: FormData = {
      ...baseForm(),
      materi: 'A',
      namaPenyusun: 'Pak H',
      tujuanPembelajaran: 'TP1',
      aspekMinat: 'lama',
    };
    const next = applyMateriChange(prev, 'B');
    expect(next.namaPenyusun).toBe('Pak H');
    expect(next.tujuanPembelajaran).toBe('TP1');
  });
});
