const esc = (s:string)=> s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
const md = (s:string)=> esc(s).replace(/\n/g,'<br>').replace(/\*\*(.*?)\*\*/g,'<b>$1</b>');
const ul = (arr:any[], fn:(x:any)=>string)=> arr.length?`<ul style="margin:6px 0 6px 18px">${arr.map(x=>`<li style="margin:2px 0">${fn(x)}</li>`).join('')}</ul>`:'<p style="color:#999">-</p>';
export const renderModulToHtml = (d:any):string => {
  let h='';
  if(d.pemahaman_bermakna) h+=`<div style="background:#f0fdf4;border-left:4px solid #16a34a;padding:10px;margin:8px 0"><b>Pemahaman Bermakna:</b><br>${md(String(d.pemahaman_bermakna))}</div>`;
  const list:any[] = Array.isArray(d?.pertemuan) ? d.pertemuan : (d?.tahap_awal||d?.tahap_inti||d?.tahap_penutup) ? [d] : [];
  for(const p of list){
    h+=`<h3 style="margin:10px 0 6px">Pertemuan ${p.nomorPertemuan??''} — ${esc(p.durasi||'')}</h3>`;
    const renderTahap=(label:string,tahap:any)=>{
      if(!tahap) return '';
      let s=`<h4 style="background:#e0e7ff;padding:4px 8px;margin:8px 0 4px">${esc(label)} — ${esc(tahap.judul||'')} <span style="font-weight:normal">(${esc(tahap.durasi_total||tahap.durasi||'')})</span></h4>`;
      const fases=tahap.fase_pembelajaran;
      if(Array.isArray(fases)&&fases.length){
        for(const f of fases){ s+=`<div style="margin:6px 0 6px 12px;border-left:3px solid #6366f1;padding-left:8px"><b>${esc(f.nama||'')} <span style="color:#6366f1">(${esc(f.durasi||'')})</span></b>`; for(const k of (f.sintaks||[])){ s+=`<div style="margin:4px 0"><b>${esc(k.sintaks||'')}</b> <span style="font-size:9pt;color:#666">(${esc(k.durasi||'')})</span>`; for(const sub of (k.sub_kegiatan||[])){ s+=`<div style="margin-left:12px">• <b>${esc(sub.judul||'')}</b>${sub.aktivitas?ul(sub.aktivitas,(a:string)=>md(a)):''}</div>`;} s+='</div>';} s+='</div>';}
      } else { for(const k of (tahap.kegiatan||[])){ s+=`<div style="margin:4px 0 4px 12px"><b>${esc(k.sintaks||'')}</b> <span style="font-size:9pt;color:#666">(${esc(k.durasi||'')})</span>`; for(const sub of (k.sub_kegiatan||[])){ s+=`<div style="margin-left:12px">• <b>${esc(sub.judul||'')}</b>${sub.aktivitas?ul(sub.aktivitas,(a:string)=>md(a)):''}</div>`;} s+='</div>';}}
      return s;
    };
    const d2:any=p;
    if('tahap_awal' in d2){ h+=renderTahap('Awal',d2.tahap_awal); h+=renderTahap('Inti',d2.tahap_inti); h+=renderTahap('Penutup',d2.tahap_penutup);}
    else { const row=(label:string,arr:any[])=> arr?.length?`<h4>${esc(label)}</h4>${ul(arr,(x:any)=>`${md(x.kegiatan||'')} <span style="color:#666">(${esc(x.durasi||'')})</span>`)}`:''; h+=row('Pembukaan',d2.pembukaan||[]); h+=row('Inti',d2.inti||[]); h+=row('Penutup',d2.penutup||[]);}
  }
  return h||`<pre style="white-space:pre-wrap;font-size:9pt;background:#f5f5f5;padding:8px;border:1px solid #ddd">${esc(JSON.stringify(d,null,2))}</pre>`;
};
export const renderLkpdToHtml=(d:any)=> `<h3>${esc(d.judul_lkpd||'LKPD')}</h3>${d.petunjuk_belajar?`<b>Petunjuk:</b>${ul(d.petunjuk_belajar,md)}`:''}${d.informasi_pendukung?`<p><b>Info:</b> ${md(String(d.informasi_pendukung))}</p>`:''}${d.pertanyaan_pemantik?`<p><b>Pertanyaan Pemantik:</b> ${md(String(d.pertanyaan_pemantik))}</p>`:''}${d.masalah_kontekstual?`<p><b>Masalah Kontekstual:</b> ${md(String(d.masalah_kontekstual))}</p>`:''}${(d.aktivitas_utama||[]).map((a:any,i:number)=>`<div style="border:1px solid #ddd;padding:8px;margin:6px 0"><b>Aktivitas ${i+1}: ${esc(a.judul||'')}</b> <span style="font-size:9pt;color:#666">(${esc(a.jenis||'')})</span><br>${a.teks_pendukung?`<p>${md(a.teks_pendukung)}</p>`:''}${a.instruksi?`<p><b>Instruksi:</b> ${md(a.instruksi)}</p>`:''}${a.pertanyaan_kunci?.length?`<b>Pertanyaan Kunci:</b>${ul(a.pertanyaan_kunci,md)}`:''}${a.format_jawaban?`<p><b>Format Jawaban:</b> ${md(a.format_jawaban)}</p>`:''}</div>`).join('')}${d.refleksi?`<h4>Refleksi</h4><b>Diri:</b>${ul(d.refleksi.diri||[],md)}<b>Sejawat:</b>${ul(d.refleksi.sejawat||[],md)}`:''}`;
export const renderAsesmenToHtml=(d:any)=> `<h3>Asesmen</h3>${d.asesmen_awal?`<div style="border:1px solid #ddd;padding:8px;margin:6px 0"><b>Awal — ${esc(d.asesmen_awal.metode||'')}</b><br>${md(d.asesmen_awal.deskripsi||'')}${ul(d.asesmen_awal.items||[],(x:any)=>`${md(x.pertanyaan||'')} <span style="color:#666">— ${esc(x.tujuan||'')}</span>` )}</div>`:''}${d.asesmen_proses?`<div style="border:1px solid #ddd;padding:8px;margin:6px 0"><b>Proses — ${esc(d.asesmen_proses.metode||'')}</b><br>${md(d.asesmen_proses.deskripsi||'')}${(d.asesmen_proses.aktivitas||[]).map((a:any)=>`<div style="margin:6px 0"><b>${esc(a.nama||'')}</b>: ${md(a.instruksi||'')}${ul(a.pertanyaan_diskusi||[],md)}</div>`).join('')}${d.asesmen_proses.rubrik?.length?`<table border="1" cellpadding="4" style="border-collapse:collapse;width:100%;font-size:9pt"><tr><th>Aspek</th><th>Sangat Baik</th><th>Baik</th><th>Cukup</th><th>Kurang</th></tr>${d.asesmen_proses.rubrik.map((r:any)=>`<tr><td>${esc(r.aspek)}</td><td>${esc(r.sangat_baik||'')}</td><td>${esc(r.baik||'')}</td><td>${esc(r.cukup||'')}</td><td>${esc(r.kurang||'')}</td></tr>`).join('')}</table>`:''}</div>`:''}${d.asesmen_akhir?`<div style="border:1px solid #ddd;padding:8px;margin:6px 0"><b>Akhir — ${esc(d.asesmen_akhir.metode||'')}</b><br>${md(d.asesmen_akhir.deskripsi||'')}<ol>${(d.asesmen_akhir.soal||[]).map((s:any)=>`<li>${md(s.pertanyaan||'')}<br><span style="color:#16a34a">Kunci: ${esc(s.kunci_jawaban||'')}</span> <span style="color:#666">(${s.skor||''} poin)</span></li>`).join('')}</ol></div>`:''}`;
export const renderMateriToHtml=(d:any)=> `<h3>${esc(d.judul_materi||'Materi')}</h3>${d.pendahuluan?`<p>${md(d.pendahuluan)}</p>`:''}${(d.isi_materi||[]).map((m:any,i:number)=>`<div style="border:1px solid #ddd;padding:8px;margin:6px 0"><b>${i+1}. ${esc(m.sub_judul||'')}</b>${m.poin_utama?`<div style="background:#fef9c3;padding:6px;margin:4px 0"><b>Poin Utama:</b> ${md(m.poin_utama)}</div>`:''}${m.penjelasan_detail?`<p>${md(m.penjelasan_detail)}</p>`:''}${m.contoh_konkret?`<div style="background:#f0fdf4;padding:6px"><b>Contoh:</b> ${md(m.contoh_konkret)}</div>`:''}${m.istilah_penting?`<p><b>Istilah:</b> ${esc(m.istilah_penting)}</p>`:''}</div>`).join('')}${d.fakta_unik?`<p><b>Fakta Unik:</b> ${md(d.fakta_unik)}</p>`:''}${d.glosarium?.length?`<h4>Glosarium</h4><table border="1" cellpadding="4" style="border-collapse:collapse;width:100%;font-size:9pt">${d.glosarium.map((g:any)=>`<tr><td><b>${esc(g.istilah)}</b></td><td>${esc(g.definisi)}</td></tr>`).join('')}</table>`:''}${d.referensi?.length?`<h4>Referensi</h4>${ul(d.referensi,esc)}`:''}`;
export const renderSoalToHtml=(d:any)=> `<h3>${esc(d.judul_latihan||'Bank Soal')}</h3>${d.stimulus?`<div style="background:#eff6ff;padding:8px;border:1px solid #bfdbfe"><b>Stimulus:</b><br>${md(d.stimulus)}</div>`:''}${d.kisi_kisi?`<p><b>KD:</b> ${esc(d.kisi_kisi.kompetensi_dasar||'')} | <b>Indikator:</b> ${(d.kisi_kisi.indikator||[]).map(esc).join(', ')}</p>`:''}<ol>${(d.daftar_soal||[]).map((s:any)=>`<li style="margin:6px 0"><div><b>[${esc(s.tipe||'')}${s.level_kognitif?` — ${esc(s.level_kognitif)}`:''}]</b> ${md(s.pertanyaan||'')}</div>${s.opsi?.length?`<ol type="A" style="margin-left:16px">${s.opsi.map((o:string)=>`<li>${md(o)}</li>`).join('')}</ol>`:''}${s.pernyataan_benar_salah?.length?`<ul>${s.pernyataan_benar_salah.map((p:any)=>`<li>${esc(p.pernyataan)} — <b>${esc(p.jawaban)}</b></li>`).join('')}</ul>`:''}${s.premis?.length?`<table border="1" cellpadding="4" style="border-collapse:collapse;font-size:9pt"><tr><th>Premis</th><th>Respon</th></tr>${s.premis.map((_:any,i:number)=>`<tr><td>${esc(s.premis[i]||'')}</td><td>${esc(s.respon?.[i]||'')}</td></tr>`).join('')}</table>`:''}<p style="color:#16a34a"><b>Kunci:</b> ${esc(Array.isArray(s.kunci)?s.kunci.join(', '):String(s.kunci||''))} | <b>Skor:</b> ${s.skor||''}</p><p style="color:#666;font-size:9pt"><b>Pembahasan:</b> ${md(s.pembahasan||'')}</p></li>`).join('')}</ol>${d.pedoman_penilaian?`<p><b>Skor Maks:</b> ${d.pedoman_penilaian.skor_maksimal} | <b>Rumus:</b> ${esc(d.pedoman_penilaian.rumus||'')}</p>`:''}`;
export const renderRefleksiToHtml=(d:any)=> `<h3>Refleksi & Tindak Lanjut</h3><b>Refleksi Guru:</b>${ul(d.refleksi_guru||[],md)}<b>Refleksi Siswa:</b>${ul(d.refleksi_siswa||[],md)}${d.remedial?`<p><b>Remedial:</b> ${md(d.remedial)}</p>`:''}${d.pengayaan?`<p><b>Pengayaan:</b> ${md(d.pengayaan)}</p>`:''}`;
export const renderDocToHtml=(type:string,data:any):string=>{
  const m:any={modul:renderModulToHtml,lkpd:renderLkpdToHtml,asesmen:renderAsesmenToHtml,materi:renderMateriToHtml,soal:renderSoalToHtml,refleksi:renderRefleksiToHtml};
  const fn=m[type];
  if(fn) try{return fn(data)}catch{ /* fallback */}
  return `<pre style="white-space:pre-wrap;font-size:9pt;background:#f5f5f5;padding:8px;border:1px solid #ddd">${esc(JSON.stringify(data,null,2))}</pre>`;
};
