// @ts-ignore
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
// @ts-ignore
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

declare const Deno: any;

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

// ============================================================
// Robust JSON sanitization and parsing (aligned with generate-content)
// ============================================================
const sanitizeJsonResponse = (text: string): string => {
  let cleaned = text.trim();
  if (cleaned.startsWith("```json")) {
    cleaned = cleaned.slice(7);
  } else if (cleaned.startsWith("```")) {
    cleaned = cleaned.slice(3);
  }
  if (cleaned.endsWith("```")) {
    cleaned = cleaned.slice(0, -3);
  }
  cleaned = cleaned.trim();

  // Fix illegal backslash escapes (e.g. LaTeX formulas)
  cleaned = cleaned.replace(/\\(?!["\\/bfnrtu])/g, "\\\\");

  // Replace literal control characters inside string
  cleaned = cleaned.replace(/[\n\r\t]+/g, " ");

  return cleaned;
};

const extractJsonFromResponse = (text: string): string => {
  const cleaned = sanitizeJsonResponse(text);
  const start = cleaned.indexOf("{");
  const end = cleaned.lastIndexOf("}");

  if (start >= 0 && end > start) {
    return cleaned.substring(start, end + 1);
  }
  return cleaned;
};

const parseGeneratedJson = (text: string): { parsed?: any; sanitized: string; error?: unknown } => {
  const sanitized = extractJsonFromResponse(text);
  try {
    return { parsed: JSON.parse(sanitized), sanitized };
  } catch (parseError) {
    try {
      const fallbackContent = sanitizeJsonResponse(text);
      return { parsed: JSON.parse(fallbackContent), sanitized: fallbackContent };
    } catch {
      try {
        let repaired = sanitizeJsonResponse(text);
        repaired = extractJsonFromResponse(repaired);

        // Remove ellipsis frequently generated by LLMs
        repaired = repaired.replace(/,\s*\.\.\./g, "");
        repaired = repaired.replace(/\.\.\.\s*,/g, "");
        repaired = repaired.replace(/\[\s*\.\.\.\s*\]/g, "[]");
        repaired = repaired.replace(/\{\s*\.\.\.\s*\}/g, "{}");
        repaired = repaired.replace(/([^"\w])\.\.\.(?=[^"\w]|$)/g, "$1null");

        // Repair unterminated trailing items in JSON array or object
        repaired = repaired.replace(/,\s*"[^"]*(?:"[^"]*)*$/, "");
        repaired = repaired.replace(/"([^"\\]|\\["\\/bfnrtu])*$/, "");
        repaired = repaired.replace(/,\s*$/, "");

        const openBraces = (repaired.match(/\{/g) || []).length;
        const closeBraces = (repaired.match(/\}/g) || []).length;
        const openBrackets = (repaired.match(/\[/g) || []).length;
        const closeBrackets = (repaired.match(/\]/g) || []).length;

        // Auto-close open brackets/braces
        if (openBrackets > closeBrackets) {
          repaired += "]".repeat(openBrackets - closeBrackets);
        }
        if (openBraces > closeBraces) {
          repaired += "}".repeat(openBraces - closeBraces);
        }

        return { parsed: JSON.parse(repaired), sanitized: repaired };
      } catch (finalError) {
        return { sanitized, error: finalError };
      }
    }
  }
};

serve(async (req: any) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const body = await req.json().catch(() => ({}));
    const {
      cp,
      mata_pelajaran,
      fase,
      kelas,
      jp_per_minggu = 4,
      minggu_efektif_sem1 = 18,
      minggu_efektif_sem2 = 18,
      tujuan_pembelajaran,
    } = body;

    if (!cp || !mata_pelajaran) {
      return new Response(JSON.stringify({ error: "CP dan Mata Pelajaran wajib diisi" }), {
        status: 200,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Auth & Key Resolution
    let userId: string | null = null;
    let isTrial = false;
    let userKeyPool: Array<{ key: string; provider: "gemini" | "grok" | "openai" }> = [];
    const demoKeyPool: Array<{ key: string; provider: "gemini" }> = [];

    const authHeader = req.headers.get("Authorization");
    const supabaseAdmin = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    if (authHeader) {
      const token = authHeader.replace("Bearer ", "");
      const { data: { user } } = await supabaseAdmin.auth.getUser(token);

      if (user) {
        userId = user.id;

        // Check account type & expiry
        const { data: customerData } = await supabaseAdmin
          .from("allowed_customers")
          .select("account_type, subscription_expires_at")
          .eq("user_id", user.id)
          .maybeSingle();

        isTrial = customerData?.account_type === "trial";

        if (
          customerData?.account_type === "annual" &&
          customerData?.subscription_expires_at &&
          new Date(customerData.subscription_expires_at).getTime() < Date.now()
        ) {
          return new Response(
            JSON.stringify({
              error: "Langganan tahunan Anda telah berakhir. Silakan perpanjang.",
              errorCode: "subscription_expired",
            }),
            { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
          );
        }

        // Fetch user active keys across all providers
        if (!isTrial) {
          const { data: profileData } = await supabaseAdmin
            .from("profiles")
            .select("preferred_provider")
            .eq("user_id", user.id)
            .maybeSingle();

          const preferredProvider = (profileData?.preferred_provider as "gemini" | "grok" | "openai" | null) || null;

          const { data: userKeys } = await supabaseAdmin
            .from("user_api_keys")
            .select("api_key, provider")
            .eq("user_id", user.id)
            .eq("is_active", true)
            .order("created_at", { ascending: true });

          if (userKeys && userKeys.length > 0) {
            const normalized = userKeys.map((k: any) => ({
              key: k.api_key as string,
              provider: ((k.provider as "gemini" | "grok" | "openai") || "gemini"),
            }));

            userKeyPool = preferredProvider
              ? [
                  ...normalized.filter((k) => k.provider === preferredProvider),
                  ...normalized.filter((k) => k.provider !== preferredProvider),
                ]
              : normalized;
          }
        }

        // Preload demo keys as fallback pool
        const { data: demoKeys } = await supabaseAdmin
          .from("demo_api_keys")
          .select("api_key")
          .eq("is_active", true)
          .order("created_at", { ascending: true });

        if (demoKeys && demoKeys.length > 0) {
          for (const dk of demoKeys) {
            demoKeyPool.push({ key: dk.api_key as string, provider: "gemini" });
          }
        }
      }
    }

    // Build the full candidate key pool: user keys first, then demo keys
    const candidateKeys = [...userKeyPool];
    if (candidateKeys.length === 0) {
      candidateKeys.push(...demoKeyPool);
    }

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");

    if (candidateKeys.length === 0 && !LOVABLE_API_KEY) {
      return new Response(
        JSON.stringify({ error: "API Key tidak tersedia. Silakan konfigurasi API Key di Pengaturan.", needApiKey: true }),
        { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const numJpPerMinggu = Number(jp_per_minggu) || 4;
    const numMingguSem1 = Number(minggu_efektif_sem1) || 18;
    const numMingguSem2 = Number(minggu_efektif_sem2) || 18;
    const totalJPSem1 = numJpPerMinggu * numMingguSem1;
    const totalJPSem2 = numJpPerMinggu * numMingguSem2;

    let tpInstruction = "";
    if (tujuan_pembelajaran && Array.isArray(tujuan_pembelajaran) && tujuan_pembelajaran.length > 0) {
      const tpStrings = tujuan_pembelajaran.map((tp) =>
        typeof tp === "object" && tp?.description ? tp.description : String(tp)
      );

      tpInstruction = `1. WAJIB GUNAKAN DAFTAR Tujuan Pembelajaran (TP) berikut SECARA UTUH tanpa mengubah redaksinya atau membuat TP baru:\n${tpStrings
        .map((tp, i) => `   - TP ${i + 1}: ${tp}`)
        .join("\n")}\n2. Kamu HANYA perlu melengkapi materi_pokok (ringkas 1-5 kata), alokasi_jp, semester (1 atau 2), dimensi_profil_lulusan (1-2 item), panca_cinta, dan keterangan untuk masing-masing TP.`;
    } else {
      tpInstruction =
        "1. Breakdown CP menjadi beberapa Tujuan Pembelajaran (TP) yang spesifik, terukur, dan operasional.\n2. Setiap TP harus memiliki materi pokok yang jelas dan ringkas (1-5 kata).";
    }

    const prompt = `Kamu adalah ahli kurikulum pendidikan Indonesia (Kurikulum Merdeka).

Berdasarkan Capaian Pembelajaran (CP) berikut untuk mata pelajaran ${mata_pelajaran}, Fase ${fase || ""}, ${kelas || ""}:

"""
${cp}
"""

Buatlah Program Tahunan (Prota) yang lengkap dan terstruktur.

Informasi JP:
- JP per minggu: ${numJpPerMinggu}
- Minggu efektif Semester 1: ${numMingguSem1} → Target Kapasitas JP Sem 1: ${totalJPSem1}
- Minggu efektif Semester 2: ${numMingguSem2} → Target Kapasitas JP Sem 2: ${totalJPSem2}

ATURAN WAJIB:
${tpInstruction}
3. Alokasi JP harus realistis. Total JP Semester 1 harus mendekati ${totalJPSem1} JP dan Semester 2 mendekati ${totalJPSem2} JP.
4. Distribusikan seluruh TP secara seimbang antara Semester 1 dan Semester 2.
5. Dimensi Profil Lulusan (DPL) pilih 1 atau 2 dari: Beriman dan Bertakwa, Beridentitas Global, Bergotong Royong, Mandiri, Bernalar Kritis, Kreatif, Berkesadaran Lingkungan, Berjiwa Wirausaha.
6. Nomor urut TP harus berurutan dari 1 sampai N (gabungan kedua semester).
7. Untuk panca_cinta, jika relevan pilih SATU dari: "Cinta kepada Allah dan Rasul-Nya", "Cinta kepada Ilmu", "Cinta kepada Diri dan Sesama Manusia", "Cinta kepada Alam dan Lingkungan", "Cinta kepada Tanah Air". Jika tidak relevan, isi string kosong "".
8. Pastikan materi_pokok ditulis ringkas (1-5 kata) agar seluruh TP tertampung dalam JSON tanpa terpotong.

Kembalikan HANYA JSON valid (tanpa markdown, tanpa teks pembuka/penutup) dengan format:
{
  "prota": [
    {
      "no": 1,
      "tujuan_pembelajaran": "Peserta didik mampu ...",
      "materi_pokok": "...",
      "alokasi_jp": 8,
      "semester": 1,
      "dimensi_profil_lulusan": ["Bernalar Kritis", "Mandiri"],
      "panca_cinta": "Cinta Ilmu",
      "keterangan": ""
    }
  ],
  "total_jp_sem1": ${totalJPSem1},
  "total_jp_sem2": ${totalJPSem2}
}`;

    // Strictly adhere to .agents/rules/api-key.md (Experimental Tier Gemini models ONLY, NEVER gemini-1.5)
    const GEMINI_MODEL_CHAIN = [
      "gemini-3.5-flash",
      "gemini-3.0-flash",
      "gemini-3.5-flash-lite",
      "gemini-2.5-flash",
      "gemini-2.5-flash-lite",
      "gemini-1.5-flash"
    ];

    let resultData: any = null;
    let usedProvider = "";
    let usedModel = "";
    let lastError = "";

    // Helper: Execute a candidate key
    const tryCandidateKey = async (entry: { key: string; provider: "gemini" | "grok" | "openai" }) => {
      if (entry.provider === "gemini") {
        for (const model of GEMINI_MODEL_CHAIN) {
          try {
            const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${entry.key}`;
            const resp = await fetch(endpoint, {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({
                contents: [{ role: "user", parts: [{ text: prompt }] }],
                generationConfig: {
                  temperature: 0.4,
                  maxOutputTokens: 8192,
                  responseMimeType: "application/json",
                },
              }),
            });

            if (resp.ok) {
              const resJson = await resp.json();
              const rawText = resJson?.candidates?.[0]?.content?.parts?.[0]?.text || "";
              const { parsed, error: pError } = parseGeneratedJson(rawText);

              if (parsed && (Array.isArray(parsed.prota) || Array.isArray(parsed))) {
                const protaList = Array.isArray(parsed.prota) ? parsed.prota : parsed;
                return {
                  success: true,
                  data: {
                    prota: protaList,
                    total_jp_sem1: parsed.total_jp_sem1 ?? totalJPSem1,
                    total_jp_sem2: parsed.total_jp_sem2 ?? totalJPSem2,
                  },
                  model,
                  provider: "gemini",
                };
              }
              console.log(`[generate-prota] JSON parse failed on ${model}:`, pError);
            } else {
              const errBody = await resp.text().catch(() => "");
              console.log(`[generate-prota] ${model} failed (${resp.status}): ${errBody.substring(0, 150)}`);
              lastError = `Gemini (${resp.status}): ${errBody.substring(0, 120)}`;
              // 404, 429, 503 are recoverable across model chain
              if (resp.status !== 429 && resp.status !== 404 && resp.status !== 503) {
                // Key level error (400, 401, 403), skip remaining models for this key
                break;
              }
            }
          } catch (e: any) {
            console.log(`[generate-prota] Network error on ${model}:`, e?.message);
            lastError = e?.message || "Network error";
          }
        }
      } else {
        // Grok or OpenAI
        const endpoint =
          entry.provider === "grok"
            ? "https://api.x.ai/v1/chat/completions"
            : "https://api.openai.com/v1/chat/completions";
        const model = entry.provider === "grok" ? "grok-4-fast-reasoning" : "gpt-4o-mini";

        try {
          const resp = await fetch(endpoint, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              Authorization: `Bearer ${entry.key}`,
            },
            body: JSON.stringify({
              model,
              messages: [{ role: "user", content: prompt }],
              max_tokens: 8192,
              response_format: { type: "json_object" },
            }),
          });

          if (resp.ok) {
            const resJson = await resp.json();
            const rawText = resJson?.choices?.[0]?.message?.content || "";
            const { parsed, error: pError } = parseGeneratedJson(rawText);

            if (parsed && (Array.isArray(parsed.prota) || Array.isArray(parsed))) {
              const protaList = Array.isArray(parsed.prota) ? parsed.prota : parsed;
              return {
                success: true,
                data: {
                  prota: protaList,
                  total_jp_sem1: parsed.total_jp_sem1 ?? totalJPSem1,
                  total_jp_sem2: parsed.total_jp_sem2 ?? totalJPSem2,
                },
                model,
                provider: entry.provider,
              };
            }
            console.log(`[generate-prota] ${entry.provider} JSON parse failed:`, pError);
          } else {
            const errBody = await resp.text().catch(() => "");
            console.log(`[generate-prota] ${entry.provider} failed (${resp.status}): ${errBody.substring(0, 150)}`);
            lastError = `${entry.provider} (${resp.status}): ${errBody.substring(0, 120)}`;
          }
        } catch (e: any) {
          console.log(`[generate-prota] Network error on ${entry.provider}:`, e?.message);
          lastError = e?.message || "Network error";
        }
      }

      return { success: false };
    };

    // 1. Iterate over candidate keys (user keys first)
    for (let i = 0; i < candidateKeys.length; i++) {
      const entry = candidateKeys[i];
      console.log(`[generate-prota] Trying key ${i + 1}/${candidateKeys.length}: ${entry.provider} ...${entry.key.slice(-4)}`);
      const result = await tryCandidateKey(entry);
      if (result.success) {
        resultData = result.data;
        usedModel = result.model!;
        usedProvider = result.provider!;
        break;
      }
    }

    // 2. If user keys failed, fallback to demo keys pool if not already tried
    if (!resultData && userKeyPool.length > 0 && demoKeyPool.length > 0) {
      console.log(`[generate-prota] User keys failed, falling back to ${demoKeyPool.length} demo keys`);
      for (const dk of demoKeyPool) {
        const result = await tryCandidateKey(dk);
        if (result.success) {
          resultData = result.data;
          usedModel = result.model!;
          usedProvider = result.provider!;
          break;
        }
      }
    }

    // 3. Fallback to Lovable AI Gateway if still not succeeded and key exists
    if (!resultData && LOVABLE_API_KEY) {
      console.log("[generate-prota] Falling back to Lovable AI Gateway");
      try {
        const gatewayUrl = "https://api.lovable.dev/v1/chat/completions";
        const resp = await fetch(gatewayUrl, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${LOVABLE_API_KEY}`,
          },
          body: JSON.stringify({
            model: "google/gemini-2.5-flash",
            messages: [{ role: "user", content: prompt }],
            temperature: 0.5,
            max_tokens: 8192,
            response_format: { type: "json_object" },
          }),
        });

        if (resp.ok) {
          const resJson = await resp.json();
          const rawText = resJson?.choices?.[0]?.message?.content || "";
          const { parsed } = parseGeneratedJson(rawText);

          if (parsed && (Array.isArray(parsed.prota) || Array.isArray(parsed))) {
            const protaList = Array.isArray(parsed.prota) ? parsed.prota : parsed;
            resultData = {
              prota: protaList,
              total_jp_sem1: parsed.total_jp_sem1 ?? totalJPSem1,
              total_jp_sem2: parsed.total_jp_sem2 ?? totalJPSem2,
            };
            usedModel = "gemini-2.5-flash";
            usedProvider = "lovable-gateway";
          }
        }
      } catch (gwError: any) {
        console.error("[generate-prota] Gateway error:", gwError?.message);
      }
    }

    if (!resultData) {
      return new Response(
        JSON.stringify({
          error: lastError
            ? `Gagal generate Prota (${lastError}). Silakan coba klik Generate Ulang lagi.`
            : "Gagal generate Prota. AI tidak dapat merespons atau kuota sementara penuh. Silakan coba lagi.",
        }),
        { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    console.log(`[generate-prota] Success using ${usedProvider}/${usedModel}`);

    // Log generation
    if (userId) {
      await supabaseAdmin.from("generation_logs").insert({
        user_id: userId,
        content_type: "prota",
        metadata: {
          mata_pelajaran,
          fase,
          kelas,
          jp_per_minggu: numJpPerMinggu,
          provider: usedProvider,
          model: usedModel,
        },
      });
    }

    return new Response(JSON.stringify({ data: resultData }), {
      status: 200,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error: any) {
    console.error("Error in generate-prota:", error);
    return new Response(
      JSON.stringify({ error: `Terjadi kesalahan internal: ${error?.message || "Error tidak diketahui"}` }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
