import { supabase } from "@/integrations/supabase/client";
import { DEFAULT_FORM_DATA } from "@/lib/constants";
import type { Workspace } from "@/types/workspace";
import type { ProsemItemDB, MeetingSlotDB } from "@/hooks/useProsemData";
import { buildPertemuanPayload, emptyResultV2 } from "@/lib/pertemuan-generation";
import type { GenerationResultV2 } from "@/types/modul";
import { toast } from "sonner";

type JenisDoc = 'modul' | 'lkpd' | 'asesmen' | 'materi' | 'soal' | 'refleksi';

// Simpan dokumen ke DB menggunakan schema yang benar:
// documents -> document_versions (via RPC) -> meeting_document_links
async function saveDocumentToWorkspace(
  userId: string,
  workspaceId: string,
  meetingId: string,
  docType: JenisDoc,
  title: string,
  contentJson: any
): Promise<boolean> {
  try {
    // Cari dokumen yang sudah ada untuk pertemuan + tipe ini
    const { data: existingLinks } = await supabase
      .from('meeting_document_links')
      .select('document_id, documents(id, document_type)')
      .eq('meeting_slot_id', meetingId);

    const existingDoc = (existingLinks || []).find(
      (link: any) => link.documents?.document_type === docType
    );

    let documentId = existingDoc?.document_id;

    if (!documentId) {
      // Buat record dokumen baru
      const { data: newDoc, error: docError } = await supabase
        .from('documents')
        .insert({
          user_id: userId,
          workspace_id: workspaceId,
          document_type: docType,
          title: title,
          source_type: 'prosem',
          status: 'ready'
        })
        .select('id')
        .single();

      if (docError) throw docError;
      documentId = newDoc.id;

      // Hubungkan ke meeting slot
      const { error: linkError } = await supabase
        .from('meeting_document_links')
        .insert({ meeting_slot_id: meetingId, document_id: documentId });

      if (linkError) throw linkError;
    }

    // Simpan versi dokumen via RPC
    const { error: rpcError } = await supabase.rpc('create_document_version', {
      p_document_id: documentId,
      p_content_json: contentJson,
      p_input_snapshot: {},
      p_generation_metadata: { source: 'workspace_direct_generate' },
      p_change_type: 'generated'
    });

    if (rpcError) throw rpcError;
    return true;
  } catch (err: any) {
    console.error(`Error saving doc ${docType}:`, err);
    return false;
  }
}

// Ekstrak auto_generated dari respons modul (berisi identifikasi murid, dll)
function extractAutoGeneratedFields(modulData: any): Record<string, any> {
  const ag = modulData?.auto_generated;
  if (!ag) return {}; // Jika tidak ada, jangan overwrite dengan string kosong
  
  return {
    aspekPengetahuanAwal: ag.identifikasi_murid?.aspek_pengetahuan_awal || ag.aspekPengetahuanAwal || '',
    aspekMinat: ag.identifikasi_murid?.aspek_minat || ag.aspekMinat || '',
    aspekLatarBelakang: ag.identifikasi_murid?.aspek_latar_belakang || ag.aspekLatarBelakang || '',
    aspekKebutuhanBelajar: ag.identifikasi_murid?.aspek_kebutuhan_belajar || ag.aspekKebutuhanBelajar || '',
    kaitanKehidupan: ag.kaitan_kehidupan || ag.kaitanKehidupan || '',
    dimensiProfilLulusan: ag.dimensi_profil_lulusan || ag.dimensiProfilLulusan || [],
    dimensiProfilLulusanDeskripsi: ag.dpl_deskripsi || ag.dimensiProfilLulusanDeskripsi || undefined,
    nilaiKarakter: ag.nilai_karakter || ag.nilaiKarakter || [],
    materiPengetahuan: {
      faktual: ag.materi_pengetahuan?.faktual || '',
      konseptual: ag.materi_pengetahuan?.konseptual || '',
      prosedural: ag.materi_pengetahuan?.prosedural || '',
      metakognitif: ag.materi_pengetahuan?.metakognitif || '',
    },
    lintasDisiplinIlmu: ag.lintas_disiplin || {},
    kemitraanPembelajaran: ag.kemitraan || {},
    lingkunganPembelajaranDetail: ag.lingkungan || {},
    pemanfaatanDigitalDetail: ag.pemanfaatan_digital || {},
    pemahamanBermakna: modulData?.pemahaman_bermakna || ag.pemahaman_bermakna || '',
    metodePembelajaran: ag.metodePembelajaran || [],
    topikPancaCinta: ag.topik_panca_cinta || ag.topikPancaCinta || [],
    topikPancaCintaDeskripsi: ag.panca_cinta_deskripsi || ag.topikPancaCintaDeskripsi || undefined,
    materiIntegrasiKBC: ag.materi_integrasi_kbc || ag.materiIntegrasiKBC || '',
  };
}

export const generateWorkspaceMeetingDirect = async (
  workspace: Workspace,
  item: ProsemItemDB,
  slot: MeetingSlotDB,
  onProgress?: (msg: string) => void
): Promise<boolean> => {
  try {
    // 1. Autentikasi
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) throw new Error('Tidak terautentikasi');

    // 2. Ambil CP & Profil guru secara paralel
    onProgress?.("Mengambil data kurikulum...");
    const [cpResult, profileResult] = await Promise.all([
      supabase.from('curriculum_plans').select('content').eq('workspace_id', workspace.id).eq('type', 'tp').maybeSingle(),
      supabase.from('profiles').select('*').eq('id', user.id).maybeSingle()
    ]);

    const cpContent = (cpResult.data?.content as any)?.cp || '';
    const profile = profileResult.data;

    const jpDuration = workspace.jp_duration_minutes ||
      (workspace.phase === 'F' || workspace.phase === 'E' ? 45 : workspace.phase === 'D' ? 40 : 35);
    const genSettings = (workspace.generation_settings || {}) as any;
    const totalMinutes = (slot.planned_jp || 2) * jpDuration;
    const tps = (item.tp_snapshot || [])
      .map((tp: any) => `${tp.code || `TP${item.sequence}`}: ${tp.description || tp.teks || ''}`)
      .filter(Boolean)
      .join('\n');

    // FormData dasar — diisi dari profil guru
    const baseFormData: any = {
      ...DEFAULT_FORM_DATA,
      namaGuru: profile?.nama_guru || profile?.full_name || '',
      namaSekolah: profile?.nama_sekolah || '',
      namaKepalaSekolah: profile?.nama_kepala_sekolah || '',
      mataPelajaran: workspace.subject,
      fase: workspace.phase,
      kelas: workspace.grade?.toString() || '',
      materi: item.materi_pokok,
      capaianPembelajaran: cpContent,
      tujuanPembelajaran: tps,
      pertemuan: [{ id: slot.id, nomorPertemuan: slot.sequence, durasi: totalMinutes.toString() }],
    };

    // 3. Kontekstualisasi CP — ringkas CP sesuai materi pertemuan ini
    onProgress?.("Meringkas CP sesuai materi...");
    try {
      const { data: cpRes } = await supabase.functions.invoke('generate-content', {
        body: { type: 'kontekstualisasi-cp', data: { ...baseFormData } }
      });
      // Fallback: coba berbagai path karena edge function bisa mengembalikan { data: { cp_kontekstual } } atau { cp_kontekstual }
      const cpKontekstual = cpRes?.data?.cp_kontekstual || cpRes?.cp_kontekstual;
      if (cpKontekstual && cpKontekstual.length > 20) {
        baseFormData.capaianPembelajaran = cpKontekstual;
        console.log('[autogen] CP berhasil diringkas:', cpKontekstual.substring(0, 80));
      } else {
        console.warn('[autogen] CP tidak diringkas — response:', JSON.stringify(cpRes)?.substring(0, 200));
      }
    } catch (e) {
      console.warn("Kontekstualisasi CP gagal, lanjut dengan CP asli", e);
    }

    // 4. AI Suggest desain — model, metode, DPL, nilai karakter (TIAP PERTEMUAN BEDA!)
    // Selalu panggil suggest untuk setiap pertemuan agar tidak monoton
    onProgress?.("Merancang strategi pembelajaran...");
    try {
      const { data: suggestRes } = await supabase.functions.invoke('generate-content', {
        // Tambahkan sedikit variasi berdasarkan nomor pertemuan agar model tidak monoton
        body: { type: 'suggest-desain-pembelajaran', data: {
          ...baseFormData,
          _pertemuanNomor: slot.sequence, // hint untuk AI bervariasi
          _totalPertemuan: item.meeting_slots?.length || 1,
        }}
      });
      const suggestion = suggestRes?.data;
      if (suggestion) {
        if (suggestion.modelPembelajaran) baseFormData.modelPembelajaran = suggestion.modelPembelajaran;
        if (suggestion.metodePembelajaran?.length > 0) baseFormData.metodePembelajaran = suggestion.metodePembelajaran;
        const dpl = suggestion.dimensiProfilLulusan || suggestion.dimensiProfilPelajarPancasila;
        if (dpl?.length > 0) baseFormData.dimensiProfilLulusan = dpl;
        if (suggestion.nilaiKarakter?.length > 0) baseFormData.nilaiKarakter = suggestion.nilaiKarakter;
        
        if (suggestion.identifikasiMurid) {
          if (!baseFormData.aspekPengetahuanAwal) baseFormData.aspekPengetahuanAwal = suggestion.identifikasiMurid.pengetahuanAwal || '';
          if (!baseFormData.aspekMinat) baseFormData.aspekMinat = suggestion.identifikasiMurid.minat || '';
          if (!baseFormData.aspekLatarBelakang) baseFormData.aspekLatarBelakang = suggestion.identifikasiMurid.latarBelakang || '';
          if (!baseFormData.aspekKebutuhanBelajar) baseFormData.aspekKebutuhanBelajar = suggestion.identifikasiMurid.kebutuhanBelajar || '';
        }
        
        if (suggestion.jenisPengetahuan) {
          baseFormData.materiPengetahuan = {
            faktual: baseFormData.materiPengetahuan?.faktual || suggestion.jenisPengetahuan.faktual || '',
            konseptual: baseFormData.materiPengetahuan?.konseptual || suggestion.jenisPengetahuan.konseptual || '',
            prosedural: baseFormData.materiPengetahuan?.prosedural || suggestion.jenisPengetahuan.prosedural || '',
            metakognitif: baseFormData.materiPengetahuan?.metakognitif || suggestion.jenisPengetahuan.metakognitif || '',
          };
        }
      }
    } catch (e) {
      console.warn("Suggest desain gagal, lanjut tanpa saran AI", e);
    }

    // 4b. AI Auto-fill (Identifikasi Murid, DPL, Nilai Karakter, Kaitan Kehidupan)
    onProgress?.("Melengkapi identifikasi murid & nilai karakter...");
    let agData: any = null;
    try {
      const { data: autoFillRes } = await supabase.functions.invoke('generate-content', {
        body: { type: 'auto-fill', data: baseFormData }
      });
      const ag = autoFillRes?.data?.auto_generated || autoFillRes?.auto_generated;
      if (ag) {
        agData = ag;
        if (ag.identifikasi_murid) {
          if (!baseFormData.aspekPengetahuanAwal) baseFormData.aspekPengetahuanAwal = ag.identifikasi_murid.aspek_pengetahuan_awal || '';
          if (!baseFormData.aspekMinat) baseFormData.aspekMinat = ag.identifikasi_murid.aspek_minat || '';
          if (!baseFormData.aspekLatarBelakang) baseFormData.aspekLatarBelakang = ag.identifikasi_murid.aspek_latar_belakang || '';
          if (!baseFormData.aspekKebutuhanBelajar) baseFormData.aspekKebutuhanBelajar = ag.identifikasi_murid.aspek_kebutuhan_belajar || '';
        }
        
        if (ag.materi_pengetahuan) {
          baseFormData.materiPengetahuan = {
            faktual: baseFormData.materiPengetahuan?.faktual || ag.materi_pengetahuan.faktual || '',
            konseptual: baseFormData.materiPengetahuan?.konseptual || ag.materi_pengetahuan.konseptual || '',
            prosedural: baseFormData.materiPengetahuan?.prosedural || ag.materi_pengetahuan.prosedural || '',
            metakognitif: baseFormData.materiPengetahuan?.metakognitif || ag.materi_pengetahuan.metakognitif || '',
          };
        }
        
        baseFormData.dimensiProfilLulusan = baseFormData.dimensiProfilLulusan?.length ? baseFormData.dimensiProfilLulusan : (ag.dimensi_profil_lulusan || []);
        baseFormData.dimensiProfilLulusanDeskripsi = ag.dpl_deskripsi || '';
        baseFormData.nilaiKarakter = baseFormData.nilaiKarakter?.length ? baseFormData.nilaiKarakter : (ag.nilai_karakter || []);
        baseFormData.kaitanKehidupan = ag.kaitan_kehidupan || '';
        baseFormData.pemahamanBermakna = ag.pemahaman_bermakna || '';
        baseFormData.topikPancaCinta = ag.topik_panca_cinta || [];
        baseFormData.topikPancaCintaDeskripsi = ag.panca_cinta_deskripsi || '';
        baseFormData.materiIntegrasiKBC = ag.materi_integrasi_kbc || '';
        
        baseFormData.lintasDisiplinIlmu = ag.lintas_disiplin || {};
        baseFormData.kemitraanPembelajaran = ag.kemitraan || {};
        baseFormData.lingkunganPembelajaranDetail = ag.lingkungan || {};
        baseFormData.pemanfaatanDigitalDetail = ag.pemanfaatan_digital || {};
      }
    } catch (e) {
      console.warn("Auto-fill gagal, lanjut tanpa auto-fill", e);
    }

    // 5. Generate setiap dokumen secara berurutan
    const currentResult: GenerationResultV2 = emptyResultV2();
    currentResult.pertemuan = [{
      id: slot.id,
      nomor: slot.sequence,
      durasiMenit: totalMinutes,
      materiPokok: item.materi_pokok,
      tujuanPertemuan: tps,
      status: {}
    }];

    const jenisDocs: JenisDoc[] = ['modul', 'lkpd', 'asesmen', 'materi', 'soal', 'refleksi'];
    const docLabels: Record<JenisDoc, string> = {
      modul: 'Modul Ajar', lkpd: 'LKPD', asesmen: 'Asesmen', materi: 'Materi', soal: 'Bank Soal', refleksi: 'Refleksi'
    };

    // Gunakan soalConfig dari pengaturan, atau gunakan default (10 soal) jika kosong
    // Kurangi jumlah default agar tidak terpotong oleh token limit AI
    const defaultSoalConfig = {
      level: 'Seimbang (LOTS & HOTS)',
      typeConfigs: {
        'Pilihan Ganda': { quantity: 5, useStimulus: true, stimulusCount: 2, useImages: false, imageCount: 0 },
        'PG Kategori Benar/Salah': { quantity: 0, useStimulus: false, stimulusCount: 0, useImages: false, imageCount: 0 },
        'PG Multiple Choice Multiple Answer': { quantity: 0, useStimulus: false, stimulusCount: 0, useImages: false, imageCount: 0 },
        'Menjodohkan': { quantity: 0, useStimulus: false, stimulusCount: 0, useImages: false, imageCount: 0 },
        'Isian Singkat': { quantity: 3, useStimulus: false, stimulusCount: 0, useImages: false, imageCount: 0 },
        'Uraian': { quantity: 2, useStimulus: false, stimulusCount: 0, useImages: false, imageCount: 0 },
      }
    };

    let soalConfig = defaultSoalConfig;
    console.log('[autogen] genSettings.soalConfig raw:', JSON.stringify(genSettings.soalConfig)?.substring(0, 300));
    if (genSettings.soalConfig && Object.keys(genSettings.soalConfig).length > 0) {
      if ('typeConfigs' in genSettings.soalConfig) {
        soalConfig = genSettings.soalConfig as any;
        console.log('[autogen] soalConfig dari settings (format baru):', JSON.stringify(soalConfig).substring(0, 200));
      } else {
        const legacy = genSettings.soalConfig as any;
        const newTypeConfigs: any = { ...defaultSoalConfig.typeConfigs };
        for (const [key, val] of Object.entries(legacy)) {
          if (typeof val === 'number') {
            newTypeConfigs[key] = { quantity: val, useStimulus: false, stimulusCount: 0, useImages: false, imageCount: 0 };
          }
        }
        soalConfig = { level: defaultSoalConfig.level, typeConfigs: newTypeConfigs };
        console.log('[autogen] soalConfig dari settings (format legacy):', JSON.stringify(soalConfig).substring(0, 200));
      }
    } else {
      console.log('[autogen] soalConfig tidak ada di settings, pakai default:', JSON.stringify(defaultSoalConfig).substring(0, 200));
    }

    const docsToGenerate = jenisDocs; // Selalu generate semua dokumen termasuk soal

    let enrichedFormData = { ...baseFormData }; // Akan diperbarui setelah modul selesai

    for (let i = 0; i < docsToGenerate.length; i++) {
      const jenis = docsToGenerate[i];
      onProgress?.(`Membuat ${docLabels[jenis]} (${i+1}/${docsToGenerate.length})...`);

      const payload = buildPertemuanPayload({
        formData: enrichedFormData,
        pertemuan: currentResult.pertemuan[0],
        totalPertemuan: 1,
        jenis,
        extra: jenis === 'soal' ? { config: soalConfig } : undefined,
      });

      // Jika pertemuan pertama dan jenis modul, paksa menggunakan type 'modul'
      // agar AI menghasilkan preface (pemahaman_bermakna, metode_pembelajaran, dll).
      if (jenis === 'modul' && slot.sequence === 1) {
        payload.type = 'modul';
        payload.data = {
          ...payload.data,
          pertemuan: [
            {
              nomorPertemuan: slot.sequence,
              durasi: `${slot.duration_minutes} menit`,
            },
          ],
        };
      }

      let resData: any = null;
      let generateErr: any = null;
      try {
        const result = await supabase.functions.invoke('generate-content', {
          body: payload
        });
        resData = result.data;
        generateErr = result.error;
        
        if (generateErr) throw new Error(generateErr.message);
        if (resData?.error) throw new Error(typeof resData.error === 'string' ? resData.error : JSON.stringify(resData.error));
        if (!resData?.data) throw new Error(`Data kosong dari server`);
      } catch (docErr: any) {
        console.error(`Gagal membuat ${jenis}:`, docErr);
        toast.error(`Gagal membuat ${docLabels[jenis]}: ${docErr.message || 'Kesalahan tidak diketahui'}`);
        continue; // Lanjut ke dokumen berikutnya
      }

      // Setelah modul selesai, perkaya formData dengan data dari respons
      if (jenis === 'modul') {
        // Jika kita menggunakan type 'modul', responsenya memiliki { pertemuan: [ obj ], pemahaman_bermakna, ... }
        // Kita perlu mengekstrak array pertemuan agar dokumen yang disimpan benar-benar objek pertemuannya.
        if (resData.data?.pertemuan && Array.isArray(resData.data.pertemuan)) {
          const { pertemuan, ...preface } = resData.data;
          resData.data = { ...pertemuan[0], ...preface }; // Gabungkan preface ke dalam objek pertemuan
        }
        
        // Baca pemahaman_bermakna dan metode_pembelajaran dari root level modul response
        if (resData.data?.pemahaman_bermakna) {
          enrichedFormData.pemahamanBermakna = resData.data.pemahaman_bermakna;
          console.log('[autogen] pemahaman_bermakna dari modul:', resData.data.pemahaman_bermakna.substring(0, 60));
        }
        if (resData.data?.metode_pembelajaran?.length > 0) {
          enrichedFormData.metodePembelajaran = resData.data.metode_pembelajaran;
          console.log('[autogen] metode_pembelajaran dari modul:', resData.data.metode_pembelajaran);
        }

        // Ekstrak auto_generated dari respons modul (dari prompt inline auto-fill)
        const modulAutoGen = resData.data?.auto_generated;
        if (modulAutoGen) {
          console.log('[autogen] auto_generated dari modul ditemukan, memperkaya formData');
          // Isi field yang masih kosong dari auto_generated yang ada di respons modul
          if (modulAutoGen.identifikasi_murid) {
            enrichedFormData.aspekPengetahuanAwal = enrichedFormData.aspekPengetahuanAwal || modulAutoGen.identifikasi_murid.aspek_pengetahuan_awal || '';
            enrichedFormData.aspekMinat = enrichedFormData.aspekMinat || modulAutoGen.identifikasi_murid.aspek_minat || '';
            enrichedFormData.aspekLatarBelakang = enrichedFormData.aspekLatarBelakang || modulAutoGen.identifikasi_murid.aspek_latar_belakang || '';
            enrichedFormData.aspekKebutuhanBelajar = enrichedFormData.aspekKebutuhanBelajar || modulAutoGen.identifikasi_murid.aspek_kebutuhan_belajar || '';
          }
          if (modulAutoGen.materi_pengetahuan) {
            enrichedFormData.materiPengetahuan = {
              faktual: enrichedFormData.materiPengetahuan?.faktual || modulAutoGen.materi_pengetahuan.faktual || '',
              konseptual: enrichedFormData.materiPengetahuan?.konseptual || modulAutoGen.materi_pengetahuan.konseptual || '',
              prosedural: enrichedFormData.materiPengetahuan?.prosedural || modulAutoGen.materi_pengetahuan.prosedural || '',
              metakognitif: enrichedFormData.materiPengetahuan?.metakognitif || modulAutoGen.materi_pengetahuan.metakognitif || '',
            };
          }
          enrichedFormData.dimensiProfilLulusan = (enrichedFormData.dimensiProfilLulusan?.length ? enrichedFormData.dimensiProfilLulusan : null)
            || modulAutoGen.dimensi_profil_lulusan || [];
          enrichedFormData.dimensiProfilLulusanDeskripsi = enrichedFormData.dimensiProfilLulusanDeskripsi || modulAutoGen.dpl_deskripsi || '';
          enrichedFormData.nilaiKarakter = (enrichedFormData.nilaiKarakter?.length ? enrichedFormData.nilaiKarakter : null)
            || modulAutoGen.nilai_karakter || [];
          enrichedFormData.kaitanKehidupan = enrichedFormData.kaitanKehidupan || modulAutoGen.kaitan_kehidupan || '';
          enrichedFormData.pemahamanBermakna = enrichedFormData.pemahamanBermakna || resData.data?.pemahaman_bermakna || modulAutoGen.pemahaman_bermakna || '';
          enrichedFormData.lintasDisiplinIlmu = Object.keys(enrichedFormData.lintasDisiplinIlmu || {}).length ? enrichedFormData.lintasDisiplinIlmu : (modulAutoGen.lintas_disiplin || {});
          enrichedFormData.kemitraanPembelajaran = Object.keys(enrichedFormData.kemitraanPembelajaran || {}).length ? enrichedFormData.kemitraanPembelajaran : (modulAutoGen.kemitraan || {});
          enrichedFormData.lingkunganPembelajaranDetail = Object.keys(enrichedFormData.lingkunganPembelajaranDetail || {}).length ? enrichedFormData.lingkunganPembelajaranDetail : (modulAutoGen.lingkungan || {});
          enrichedFormData.pemanfaatanDigitalDetail = Object.keys(enrichedFormData.pemanfaatanDigitalDetail || {}).length ? enrichedFormData.pemanfaatanDigitalDetail : (modulAutoGen.pemanfaatan_digital || {});
        }

        // Bangun modulPreface dari agData atau modulAutoGen
        const agSource = modulAutoGen || agData;
        if (resData.data.modulPreface) {
          currentResult.modulPreface = resData.data.modulPreface;
        } else if (agSource) {
          currentResult.modulPreface = {
            pemahaman_bermakna: enrichedFormData.pemahamanBermakna || resData.data?.pemahaman_bermakna || '',
            auto_generated: {
              identifikasi_murid: agSource.identifikasi_murid || {
                aspek_pengetahuan_awal: enrichedFormData.aspekPengetahuanAwal,
                aspek_minat: enrichedFormData.aspekMinat,
                aspek_latar_belakang: enrichedFormData.aspekLatarBelakang,
                aspek_kebutuhan_belajar: enrichedFormData.aspekKebutuhanBelajar,
              },
              materi_pengetahuan: agSource.materi_pengetahuan || enrichedFormData.materiPengetahuan,
              dimensi_profil_lulusan: enrichedFormData.dimensiProfilLulusan || [],
              dpl_deskripsi: enrichedFormData.dimensiProfilLulusanDeskripsi || '',
              nilai_karakter: enrichedFormData.nilaiKarakter || [],
              kaitan_kehidupan: enrichedFormData.kaitanKehidupan || '',
              lintas_disiplin: agSource.lintas_disiplin || enrichedFormData.lintasDisiplinIlmu || {},
              kemitraan: agSource.kemitraan || enrichedFormData.kemitraanPembelajaran || {},
              lingkungan: agSource.lingkungan || enrichedFormData.lingkunganPembelajaranDetail || {},
              pemanfaatan_digital: agSource.pemanfaatan_digital || enrichedFormData.pemanfaatanDigitalDetail || {},
              topik_panca_cinta: enrichedFormData.topikPancaCinta || [],
              panca_cinta_deskripsi: enrichedFormData.topikPancaCintaDeskripsi || '',
              materi_integrasi_kbc: enrichedFormData.materiIntegrasiKBC || ''
            }
          };
        }
        
        // Inject auto_generated ke dalam konten modul agar tersimpan ke DB
        if (currentResult.modulPreface?.auto_generated) {
          resData.data.auto_generated = currentResult.modulPreface.auto_generated;
        }
        // Tambahkan pemahaman_bermakna ke data modul jika belum ada
        if (!resData.data.pemahaman_bermakna && enrichedFormData.pemahamanBermakna) {
          resData.data.pemahaman_bermakna = enrichedFormData.pemahamanBermakna;
        }

        // Simpan enrichedFormData yang sudah diperkaya ke generation_settings
        await supabase
          .from('workspaces')
          .update({ 
            generation_settings: {
              ...(workspace.generation_settings || {}),
              formData: enrichedFormData as any
            }
          })
          .eq('id', workspace.id);
      }

      // Simpan ke result
      const keyMap: Record<string, string> = {
        modul: 'modul', lkpd: 'lkpd', asesmen: 'asesmen', materi: 'materi', soal: 'bankSoal', refleksi: 'refleksi'
      };
      (currentResult.pertemuan[0] as any)[keyMap[jenis]] = resData.data;
      (currentResult.pertemuan[0].status as any)[jenis] = 'ok';

      // 6. Simpan ke DB langsung setiap dokumen selesai
      onProgress?.(`Menyimpan ${docLabels[jenis]}...`);
      const docTitle = `${docLabels[jenis]} - ${item.materi_pokok} (Pertemuan ${slot.sequence})`;
      await saveDocumentToWorkspace(user.id, workspace.id, slot.id, jenis, docTitle, resData.data);
    }

    // 7. Update status pertemuan menjadi completed
    onProgress?.("Menyelesaikan...");
    await supabase.from('meeting_slots').update({ status: 'completed' }).eq('id', slot.id);

    const totalDocs = docsToGenerate.length;
    toast.success(`✅ Pertemuan ${slot.sequence} selesai! ${totalDocs} dokumen berhasil dibuat.`);
    return true;
  } catch (err: any) {
    console.error("Direct generation failed:", err);
    toast.error(`Gagal: ${err.message || 'Kesalahan tidak diketahui'}`);
    return false;
  }
};
