import { supabase } from "@/integrations/supabase/client";
import { DEFAULT_FORM_DATA } from "@/lib/constants";
import type { Workspace } from "@/types/workspace";
import type { ProsemItemDB, MeetingSlotDB } from "@/hooks/useProsemData";
import { buildPertemuanPayload, emptyResultV2 } from "@/lib/pertemuan-generation";
import type { GenerationResultV2 } from "@/types/modul";
import { toast } from "sonner";

type JenisDoc = 'modul' | 'lkpd' | 'asesmen' | 'materi' | 'soal';

// Simpan dokumen ke DB menggunakan schema yang benar:
// documents -> document_versions (via RPC) -> meeting_document_links
async function saveDocumentToWorkspace(
  userId: string,
  workspaceId: string,
  meetingId: string,
  docType: JenisDoc,
  title: string,
  contentJson: any
): Promise<boolean> {
  try {
    // Cari dokumen yang sudah ada untuk pertemuan + tipe ini
    const { data: existingLinks } = await supabase
      .from('meeting_document_links')
      .select('document_id, documents(id, document_type)')
      .eq('meeting_slot_id', meetingId);

    const existingDoc = (existingLinks || []).find(
      (link: any) => link.documents?.document_type === docType
    );

    let documentId = existingDoc?.document_id;

    if (!documentId) {
      // Buat record dokumen baru
      const { data: newDoc, error: docError } = await supabase
        .from('documents')
        .insert({
          user_id: userId,
          workspace_id: workspaceId,
          document_type: docType,
          title: title,
          source_type: 'prosem',
          status: 'ready'
        })
        .select('id')
        .single();

      if (docError) throw docError;
      documentId = newDoc.id;

      // Hubungkan ke meeting slot
      const { error: linkError } = await supabase
        .from('meeting_document_links')
        .insert({ meeting_slot_id: meetingId, document_id: documentId });

      if (linkError) throw linkError;
    }

    // Simpan versi dokumen via RPC
    const { error: rpcError } = await supabase.rpc('create_document_version', {
      p_document_id: documentId,
      p_content_json: contentJson,
      p_input_snapshot: {},
      p_generation_metadata: { source: 'workspace_direct_generate' },
      p_change_type: 'generated'
    });

    if (rpcError) throw rpcError;
    return true;
  } catch (err: any) {
    console.error(`Error saving doc ${docType}:`, err);
    return false;
  }
}

// Ekstrak auto_generated dari respons modul (berisi identifikasi murid, dll)
function extractAutoGeneratedFields(modulData: any): Record<string, any> {
  const ag = modulData?.auto_generated;
  if (!ag) return {}; // Jika tidak ada, jangan overwrite dengan string kosong
  
  return {
    aspekPengetahuanAwal: ag.identifikasi_murid?.aspek_pengetahuan_awal || ag.aspekPengetahuanAwal || '',
    aspekMinat: ag.identifikasi_murid?.aspek_minat || ag.aspekMinat || '',
    aspekLatarBelakang: ag.identifikasi_murid?.aspek_latar_belakang || ag.aspekLatarBelakang || '',
    aspekKebutuhanBelajar: ag.identifikasi_murid?.aspek_kebutuhan_belajar || ag.aspekKebutuhanBelajar || '',
    kaitanKehidupan: ag.kaitan_kehidupan || ag.kaitanKehidupan || '',
    dimensiProfilLulusan: ag.dimensi_profil_lulusan || ag.dimensiProfilLulusan || [],
    nilaiKarakter: ag.nilai_karakter || ag.nilaiKarakter || [],
    materiPengetahuan: {
      faktual: ag.materi_pengetahuan?.faktual || '',
      konseptual: ag.materi_pengetahuan?.konseptual || '',
      prosedural: ag.materi_pengetahuan?.prosedural || '',
      metakognitif: ag.materi_pengetahuan?.metakognitif || '',
    },
    lintasDisiplinIlmu: ag.lintas_disiplin || {},
    kemitraanPembelajaran: ag.kemitraan || {},
    lingkunganPembelajaranDetail: ag.lingkungan || {},
    pemanfaatanDigitalDetail: ag.pemanfaatan_digital || {},
    pemahamanBermakna: modulData?.pemahaman_bermakna || ag.pemahaman_bermakna || '',
    metodePembelajaran: ag.metodePembelajaran || [],
  };
}

export const generateWorkspaceMeetingDirect = async (
  workspace: Workspace,
  item: ProsemItemDB,
  slot: MeetingSlotDB,
  onProgress?: (msg: string) => void
): Promise<boolean> => {
  try {
    // 1. Autentikasi
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) throw new Error('Tidak terautentikasi');

    // 2. Ambil CP & Profil guru secara paralel
    onProgress?.("Mengambil data kurikulum...");
    const [cpResult, profileResult] = await Promise.all([
      supabase.from('curriculum_plans').select('content').eq('workspace_id', workspace.id).eq('type', 'cp').maybeSingle(),
      supabase.from('profiles').select('*').eq('id', user.id).maybeSingle()
    ]);

    const cpContent = (cpResult.data?.content as any)?.cp || '';
    const profile = profileResult.data;

    const jpDuration = workspace.jp_duration_minutes ||
      (workspace.phase === 'F' || workspace.phase === 'E' ? 45 : workspace.phase === 'D' ? 40 : 35);
    const genSettings = (workspace.generation_settings || {}) as any;
    const totalMinutes = (slot.planned_jp || 2) * jpDuration;
    const tps = (item.tp_snapshot || [])
      .map((tp: any) => `${tp.code || `TP${item.sequence}`}: ${tp.description || tp.teks || ''}`)
      .filter(Boolean)
      .join('\n');

    // FormData dasar — diisi dari profil guru
    const baseFormData: any = {
      ...DEFAULT_FORM_DATA,
      namaGuru: profile?.nama_guru || profile?.full_name || '',
      namaSekolah: profile?.nama_sekolah || '',
      namaKepalaSekolah: profile?.nama_kepala_sekolah || '',
      mataPelajaran: workspace.subject,
      fase: workspace.phase,
      kelas: workspace.grade?.toString() || '',
      materi: item.materi_pokok,
      capaianPembelajaran: cpContent,
      tujuanPembelajaran: tps,
      pertemuan: [{ id: slot.id, nomorPertemuan: slot.sequence, durasi: totalMinutes.toString() }],
    };

    // 3. Kontekstualisasi CP — ringkas CP sesuai materi pertemuan ini
    onProgress?.("Meringkas CP sesuai materi...");
    try {
      const { data: cpRes } = await supabase.functions.invoke('generate-content', {
        body: { type: 'kontekstualisasi-cp', data: { ...baseFormData } }
      });
      const cpKontekstual = cpRes?.data?.cp_kontekstual;
      if (cpKontekstual && cpKontekstual.length > 20) {
        baseFormData.capaianPembelajaran = cpKontekstual;
      }
    } catch (e) {
      console.warn("Kontekstualisasi CP gagal, lanjut dengan CP asli", e);
    }

    // 4. AI Suggest desain — model, metode, DPL, nilai karakter (TIAP PERTEMUAN BEDA!)
    // Selalu panggil suggest untuk setiap pertemuan agar tidak monoton
    onProgress?.("Merancang strategi pembelajaran...");
    try {
      const { data: suggestRes } = await supabase.functions.invoke('generate-content', {
        // Tambahkan sedikit variasi berdasarkan nomor pertemuan agar model tidak monoton
        body: { type: 'suggest-desain-pembelajaran', data: {
          ...baseFormData,
          _pertemuanNomor: slot.sequence, // hint untuk AI bervariasi
          _totalPertemuan: item.meeting_slots?.length || 1,
        }}
      });
      const suggestion = suggestRes?.data;
      if (suggestion) {
        if (suggestion.modelPembelajaran) baseFormData.modelPembelajaran = suggestion.modelPembelajaran;
        if (suggestion.metodePembelajaran?.length > 0) baseFormData.metodePembelajaran = suggestion.metodePembelajaran;
        const dpl = suggestion.dimensiProfilLulusan || suggestion.dimensiProfilPelajarPancasila;
        if (dpl?.length > 0) baseFormData.dimensiProfilLulusan = dpl;
        if (suggestion.nilaiKarakter?.length > 0) baseFormData.nilaiKarakter = suggestion.nilaiKarakter;
        
        if (suggestion.identifikasiMurid) {
          if (!baseFormData.aspekPengetahuanAwal) baseFormData.aspekPengetahuanAwal = suggestion.identifikasiMurid.pengetahuanAwal || '';
          if (!baseFormData.aspekMinat) baseFormData.aspekMinat = suggestion.identifikasiMurid.minat || '';
          if (!baseFormData.aspekLatarBelakang) baseFormData.aspekLatarBelakang = suggestion.identifikasiMurid.latarBelakang || '';
          if (!baseFormData.aspekKebutuhanBelajar) baseFormData.aspekKebutuhanBelajar = suggestion.identifikasiMurid.kebutuhanBelajar || '';
        }
        
        if (suggestion.jenisPengetahuan) {
          baseFormData.materiPengetahuan = {
            faktual: baseFormData.materiPengetahuan?.faktual || suggestion.jenisPengetahuan.faktual || '',
            konseptual: baseFormData.materiPengetahuan?.konseptual || suggestion.jenisPengetahuan.konseptual || '',
            prosedural: baseFormData.materiPengetahuan?.prosedural || suggestion.jenisPengetahuan.prosedural || '',
            metakognitif: baseFormData.materiPengetahuan?.metakognitif || suggestion.jenisPengetahuan.metakognitif || '',
          };
        }
      }
    } catch (e) {
      console.warn("Suggest desain gagal, lanjut tanpa saran AI", e);
    }

    // 5. Generate setiap dokumen secara berurutan
    const currentResult: GenerationResultV2 = emptyResultV2();
    currentResult.pertemuan = [{
      id: slot.id,
      nomor: slot.sequence,
      durasiMenit: totalMinutes,
      materiPokok: item.materi_pokok,
      tujuanPertemuan: tps,
      status: {}
    }];

    const jenisDocs: JenisDoc[] = ['modul', 'lkpd', 'asesmen', 'materi', 'soal'];
    const docLabels: Record<JenisDoc, string> = {
      modul: 'Modul Ajar', lkpd: 'LKPD', asesmen: 'Asesmen', materi: 'Materi', soal: 'Bank Soal'
    };

    // Gunakan soalConfig dari pengaturan, atau gunakan default (15 PG, 5 Isian, 5 Uraian) jika kosong
    const soalConfig = (!!genSettings.soalConfig && Object.keys(genSettings.soalConfig).length > 0)
      ? genSettings.soalConfig
      : {
          level: 'Seimbang (LOTS & HOTS)',
          typeConfigs: {
            'Pilihan Ganda': { quantity: 15, useStimulus: true, stimulusCount: 5, useImages: false, imageCount: 0 },
            'PG Kategori Benar/Salah': { quantity: 0, useStimulus: false, stimulusCount: 0, useImages: false, imageCount: 0 },
            'PG Multiple Choice Multiple Answer': { quantity: 0, useStimulus: false, stimulusCount: 0, useImages: false, imageCount: 0 },
            'Menjodohkan': { quantity: 0, useStimulus: false, stimulusCount: 0, useImages: false, imageCount: 0 },
            'Isian Singkat': { quantity: 5, useStimulus: false, stimulusCount: 0, useImages: false, imageCount: 0 },
            'Uraian': { quantity: 5, useStimulus: false, stimulusCount: 0, useImages: false, imageCount: 0 },
          }
        };

    const docsToGenerate = jenisDocs; // Selalu generate semua dokumen termasuk soal

    let enrichedFormData = { ...baseFormData }; // Akan diperbarui setelah modul selesai

    for (let i = 0; i < docsToGenerate.length; i++) {
      const jenis = docsToGenerate[i];
      onProgress?.(`Membuat ${docLabels[jenis]} (${i+1}/${docsToGenerate.length})...`);

      const payload = buildPertemuanPayload({
        formData: enrichedFormData,
        pertemuan: currentResult.pertemuan[0],
        totalPertemuan: 1,
        jenis,
        extra: jenis === 'soal' ? { config: soalConfig } : undefined,
      });

      const { data: resData, error: err } = await supabase.functions.invoke('generate-content', {
        body: payload
      });

      if (err) throw new Error(`generate-content error (${jenis}): ${err.message}`);
      if (resData?.error) throw new Error(`Server error (${jenis}): ${JSON.stringify(resData.error)}`);
      if (!resData?.data) throw new Error(`Data kosong dari server untuk ${jenis}`);

      // Setelah modul selesai, perkaya formData dengan auto_generated
      // agar dokumen berikutnya (LKPD, Asesmen, dll) bisa pakai data yang konsisten
      if (jenis === 'modul') {
        const autoFields = extractAutoGeneratedFields(resData.data);
        enrichedFormData = {
          ...enrichedFormData,
          ...autoFields,
        };
        // Simpan juga ke currentResult untuk referensi
        if (resData.data.modulPreface) {
          currentResult.modulPreface = resData.data.modulPreface;
        }

        // Simpan autoFields ke generation_settings di tabel workspaces agar persisten dan tampil di editor
        await supabase
          .from('workspaces')
          .update({ 
            generation_settings: {
              ...(workspace.generation_settings || {}),
              formData: enrichedFormData as any
            }
          })
          .eq('id', workspace.id);

        // ALSO persist to generation_result so WorkspaceMeetingEditor can load it
        await supabase.from('generation_result').upsert({
          workspace_id: workspace.id,
          pertemuan_id: slot.id,
          jenis_dokumen: 'form_data',
          content_json: enrichedFormData as any,
          status: 'ok',
        }, { onConflict: 'workspace_id, pertemuan_id, jenis_dokumen' });
      }

      // Simpan ke result
      const keyMap: Record<JenisDoc, string> = {
        modul: 'modul', lkpd: 'lkpd', asesmen: 'asesmen', materi: 'materi', soal: 'bankSoal'
      };
      (currentResult.pertemuan[0] as any)[keyMap[jenis]] = resData.data;
      (currentResult.pertemuan[0].status as any)[jenis] = 'ok';

      // 6. Simpan ke DB langsung setiap dokumen selesai
      onProgress?.(`Menyimpan ${docLabels[jenis]}...`);
      const docTitle = `${docLabels[jenis]} - ${item.materi_pokok} (Pertemuan ${slot.sequence})`;
      await saveDocumentToWorkspace(user.id, workspace.id, slot.id, jenis, docTitle, resData.data);
    }

    // 7. Update status pertemuan menjadi completed
    onProgress?.("Menyelesaikan...");
    await supabase.from('meeting_slots').update({ status: 'completed' }).eq('id', slot.id);

    const totalDocs = docsToGenerate.length;
    toast.success(`✅ Pertemuan ${slot.sequence} selesai! ${totalDocs} dokumen berhasil dibuat.`);
    return true;
  } catch (err: any) {
    console.error("Direct generation failed:", err);
    toast.error(`Gagal: ${err.message || 'Kesalahan tidak diketahui'}`);
    return false;
  }
};
