import React, { useState, useEffect } from "react";
import { ArrowLeft, RefreshCw, BookOpen, Layers, Calendar, Settings, AlertTriangle } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { WorkspaceSettingsModal } from "../WorkspaceSettingsModal";
import { useProsemData } from "@/hooks/useProsemData";
import type { Workspace } from "@/types/workspace";
import { SemesterPlanView } from "./SemesterPlanView";
import { ProtaProsemViewerModal } from "./ProtaProsemViewerModal";
import type { MeetingSlotDB } from "@/hooks/useProsemData";
import { supabase } from "@/integrations/supabase/client";
import { useWorkspace } from "@/contexts/WorkspaceContext";
import { AutoGenerateConfirmModal } from "./AutoGenerateConfirmModal";
import { useAuth } from "@/contexts/AuthContext";
import { generateWorkspaceModul } from "./generateWorkspaceModul";
import { generateWorkspaceMeetingDirect } from "./generateWorkspaceMeetingDirect";

interface WorkspaceExplorerShellProps {
  workspace: Workspace;
  onStartPlanning?: (step?: number) => void;
  onMeetingClick?: (slot: MeetingSlotDB) => void;
  isLocked?: boolean;
  onShowUpsell?: () => void;
  onEnqueuePertemuanV2?: () => Promise<boolean>;
}

export const WorkspaceExplorerShell: React.FC<WorkspaceExplorerShellProps> = ({
  workspace,
  onStartPlanning,
  onMeetingClick,
  isLocked,
  onShowUpsell,
  onEnqueuePertemuanV2,
}) => {
  const navigate = useNavigate();
  const [isViewerOpen, setIsViewerOpen] = useState(false);
  const [isSettingsOpen, setIsSettingsOpen] = useState(false);
  const [isEnqueuing, setIsEnqueuing] = useState(false);
  const [queueStats, setQueueStats] = useState({ pending: 0, processing: 0, completed: 0, failed: 0, total: 0 });
  const [isQueueLoading, setIsQueueLoading] = useState(true);
  const [isAutoGenerateModalOpen, setIsAutoGenerateModalOpen] = useState(false);
  const [autogenQuota, setAutogenQuota] = useState({ used: 0, limit: 10, isCurrentUsed: false });
  const { prosemPlans, prosemItems, isLoading, error, refresh } = useProsemData(workspace.id);
  const { refreshWorkspaces } = useWorkspace();
  const { user, isAdmin } = useAuth();
  
  const canAccessAutoGenerate = isAdmin || user?.email === 'jagofeed@gmail.com';

  useEffect(() => {
    if (!workspace?.id) return;
    
    const fetchQueueStats = async () => {
      const { data, error } = await supabase
        .from('generation_queue')
        .select('status')
        .eq('workspace_id', workspace.id);
        
      if (!error && data) {
        const stats = data.reduce((acc, curr) => {
          acc[curr.status as keyof typeof acc] = (acc[curr.status as keyof typeof acc] || 0) + 1;
          acc.total++;
          return acc;
        }, { pending: 0, processing: 0, completed: 0, failed: 0, total: 0 });
        
        setQueueStats((prev) => {
          if ((prev.pending > 0 || prev.processing > 0) && stats.pending === 0 && stats.processing === 0 && stats.total > 0) {
            refreshWorkspaces();
            refresh();
          }
          return stats;
        });
      }
      setIsQueueLoading(false);
    };
    
    const fetchQuota = async () => {
      // In a real app we might fetch user's max_quota, but for now it's hardcoded to 10
      const { data: workspaces, error } = await supabase
        .from('workspaces')
        .select('id, is_autogenerated');
        
      if (!error && workspaces) {
        const usedWorkspaces = workspaces.filter(w => w.is_autogenerated);
        const isCurrent = usedWorkspaces.some(w => w.id === workspace.id);
        setAutogenQuota({
          used: usedWorkspaces.length,
          limit: 10,
          isCurrentUsed: isCurrent,
        });
      }
    };

    fetchQueueStats();
    fetchQuota();
    
    const channel = supabase.channel('generation_queue_changes_shell')
      .on('postgres_changes', { event: '*', schema: 'public', table: 'generation_queue', filter: `workspace_id=eq.${workspace.id}` }, () => {
        fetchQueueStats();
      })
      .subscribe();
      
    return () => {
      supabase.removeChannel(channel);
    };
  }, [workspace?.id, refreshWorkspaces, refresh]);

  // Auto-resume stuck queue
  useEffect(() => {
    // Jika ada antrean tapi tidak ada yang diproses, asumsikan webhook terhenti dan trigger manual
    if (queueStats.pending > 0 && queueStats.processing === 0 && canAccessAutoGenerate) {
      const timer = setTimeout(() => {
        console.log("Memicu ulang process-generation-queue karena antrean terhenti...");
        supabase.functions.invoke('process-generation-queue').catch(console.error);
      }, 5000);
      return () => clearTimeout(timer);
    }
  }, [queueStats.pending, queueStats.processing, canAccessAutoGenerate]);

  const totalTopics = Object.values(prosemItems).reduce((s, items) => s + items.length, 0);
  const totalJp = Object.values(prosemItems).reduce(
    (s, items) => s + items.reduce((ss, i) => ss + i.allocated_jp, 0),
    0
  );
  const totalMeetings = Object.values(prosemItems).reduce(
    (s, items) => s + items.reduce((ss, i) => ss + i.meeting_slots.length, 0),
    0
  );
  const completedMeetings = Object.values(prosemItems).reduce(
    (s, items) => s + items.reduce((ss, i) => ss + i.meeting_slots.filter(m => m.status === "completed").length, 0),
    0
  );
  const completedJp = Object.values(prosemItems).reduce(
    (s, items) => s + items.reduce((ss, i) => ss + i.meeting_slots.filter(m => m.status === "completed").reduce((sss, m) => sss + m.planned_jp, 0), 0),
    0
  );
  const overallProgress = totalJp > 0 ? Math.round((completedJp / totalJp) * 100) : 0;

  return (
    <div className="w-full max-w-4xl mx-auto p-4 md:p-6 space-y-6 pb-24 animate-fade-in">
      {/* Top Navigation */}
      <div className="flex items-center gap-3">
        <button
          onClick={() => navigate("/app/workspace")}
          className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors group"
        >
          <ArrowLeft className="w-4 h-4 group-hover:-translate-x-0.5 transition-transform" />
          Semua Workspace
        </button>
        <span className="text-muted-foreground/40">/</span>
        <span className="text-sm font-medium truncate flex items-center gap-2">
          {workspace.subject}
          {isLocked ? (
            <span className="px-1.5 py-0.5 rounded text-[10px] font-bold bg-amber-100 text-amber-700 border border-amber-300">PREVIEW</span>
          ) : (
            <span className="px-1.5 py-0.5 rounded text-[10px] font-bold bg-yellow-100 text-yellow-700 border border-yellow-300">👑 PRO</span>
          )}
        </span>
      </div>

      {/* Workspace Identity Header */}
      <div className="workspace-card">
        <div className="space-y-1">
          <h1 className="workspace-title">{workspace.subject}</h1>
          <p className="workspace-meta">
            Kelas {workspace.grade} · Fase {workspace.phase} · {workspace.academic_year}
          </p>
          {workspace.school_name && (
            <p className="text-xs text-muted-foreground font-semibold">{workspace.school_name}</p>
          )}
          <div className="flex items-center gap-2 mt-2">
            <button
              onClick={() => setIsViewerOpen(true)}
              className="inline-flex items-center gap-2 px-3 py-1.5 text-xs font-semibold bg-primary/10 text-primary hover:bg-primary/20 border-2 border-transparent hover:border-primary/30 rounded-md transition-colors"
            >
              <BookOpen className="w-3.5 h-3.5" />
              Lihat Prota & Prosem
            </button>
            <button
              onClick={() => setIsSettingsOpen(true)}
              className="inline-flex items-center gap-2 px-3 py-1.5 text-xs font-semibold bg-muted text-muted-foreground hover:bg-muted/80 border-2 border-transparent hover:border-foreground/20 rounded-md transition-colors"
            >
              <Settings className="w-3.5 h-3.5" />
              Pengaturan Workspace
            </button>
          </div>
        </div>

        {/* Overall Progress Ring - NeoBrutalism style adjustment */}
        <div className="flex items-center gap-4">
          <div className="relative w-16 h-16 bg-white rounded-full border-2 border-foreground shadow-brutal-sm flex items-center justify-center">
            <svg viewBox="0 0 36 36" className="w-14 h-14 -rotate-90 absolute">
              <circle cx="18" cy="18" r="14" fill="none" strokeWidth="4" className="stroke-muted" />
              <circle
                cx="18" cy="18" r="14" fill="none" strokeWidth="4"
                strokeDasharray={`${overallProgress * 0.879} 87.9`}
                className="stroke-primary transition-all duration-700"
                strokeLinecap="butt"
              />
            </svg>
            <span className="text-sm font-black z-10">{overallProgress}%</span>
          </div>

          <div className="space-y-1 text-sm">
            <div className="flex items-center gap-2">
              <Layers className="w-3.5 h-3.5 text-muted-foreground" />
              <span className="text-muted-foreground">{totalTopics} topik</span>
            </div>
            <div className="flex items-center gap-2">
              <Calendar className="w-3.5 h-3.5 text-muted-foreground" />
              <span className="text-muted-foreground">{completedMeetings} pertemuan selesai</span>
            </div>
            <div className="flex items-center gap-2">
              <BookOpen className="w-3.5 h-3.5 text-muted-foreground" />
              <span className="text-muted-foreground">{totalJp} JP total</span>
            </div>
          </div>
        </div>
      </div>

      {/* Auto-Generate Banner */}
      {canAccessAutoGenerate && totalMeetings - completedMeetings > 0 && (
        <div className="p-4 bg-amber-50 border-2 border-amber-200 rounded-xl flex flex-col gap-3 shadow-sm">
          <div className="flex gap-3 items-start">
            <AlertTriangle className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
            <div className="flex-1">
              <p className="text-sm font-bold text-amber-800">Perhatian</p>
              <p className="text-sm text-amber-700 mt-0.5">Ada {totalMeetings - completedMeetings} pertemuan yang belum mempunyai Modul Ajar.</p>
              
              {/* Show progress indicator if queue is loading OR if there are active items */}
              {(isQueueLoading || queueStats.pending > 0 || queueStats.processing > 0) ? (
                <div className="mt-3 text-sm text-amber-900 bg-amber-100/50 p-3 rounded-lg border border-amber-200/50">
                  <p className="font-semibold flex items-center gap-2">
                    <RefreshCw className="w-4 h-4 animate-spin" />
                    <span>Memproses antrean dokumen...</span>
                  </p>
                  <div className="flex gap-4 mt-3 text-xs font-medium text-amber-800">
                    <span className="flex items-center gap-1.5"><div className="w-2 h-2 rounded-full bg-amber-400"></div> {queueStats.pending} menunggu</span>
                    <span className="flex items-center gap-1.5"><div className="w-2 h-2 rounded-full bg-blue-400 animate-pulse"></div> {queueStats.processing} diproses</span>
                  </div>
                </div>
              ) : (
                onEnqueuePertemuanV2 && (
                  <button
                    className="inline-flex items-center justify-center gap-2 px-4 py-2 mt-3 text-sm font-semibold text-white bg-amber-600 hover:bg-amber-700 rounded-lg transition-colors border border-amber-700 shadow-sm disabled:opacity-50"
                    disabled={isEnqueuing}
                    onClick={() => {
                      setIsAutoGenerateModalOpen(true);
                    }}
                  >
                    {isEnqueuing ? (
                      <><RefreshCw className="w-4 h-4 animate-spin" /> Memproses...</>
                    ) : (
                      'Auto-Generate di Latar Belakang (Server)'
                    )}
                  </button>
                )
              )}
            </div>
          </div>
        </div>
      )}

      {/* Loading / Error State */}
      {isLoading && (
        <div className="flex items-center justify-center py-16">
          <RefreshCw className="w-8 h-8 text-primary animate-spin" />
        </div>
      )}

      {error && (
        <div className="bg-rose-50 dark:bg-rose-950/30 border-2 border-rose-300 rounded-2xl p-5 text-center space-y-2">
          <p className="text-rose-600 font-semibold">Gagal memuat data Program Semester</p>
          <p className="text-sm text-rose-500">{error}</p>
          <button
            onClick={refresh}
            className="mt-2 inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-rose-500 text-white text-sm font-medium hover:bg-rose-600 transition-colors"
          >
            <RefreshCw className="w-4 h-4" /> Coba Lagi
          </button>
        </div>
      )}

      {/* Empty: no prosem plans */}
      {!isLoading && !error && prosemPlans.length === 0 && (
        <div className="border-2 border-dashed border-foreground/20 rounded-2xl p-12 text-center space-y-4">
          <BookOpen className="w-12 h-12 text-muted-foreground/40 mx-auto" />
          <div>
            <h3 className="text-lg font-bold">Belum ada Program Semester</h3>
            <p className="text-sm text-muted-foreground max-w-sm mx-auto mt-1">
              Susun perencanaan pembelajaran Workspace ini terlebih dahulu:<br />
              CP / TP → Prota → Program Semester → Topik & Pertemuan.
            </p>
          </div>
          {onStartPlanning && (
            <button
              onClick={isLocked && onShowUpsell ? onShowUpsell : () => onStartPlanning()}
              className={`inline-flex items-center gap-2 px-5 py-2.5 rounded-xl font-semibold text-sm transition-colors shadow ${
                isLocked 
                  ? 'bg-amber-500 text-white hover:bg-amber-600'
                  : 'bg-primary text-primary-foreground hover:bg-primary/90'
              }`}
            >
              {isLocked ? '🔒 Upgrade untuk Perencanaan' : 'Mulai Perencanaan'}
            </button>
          )}
        </div>
      )}

      {/* Semester Plans */}
      {!isLoading && !error && prosemPlans.map((plan) => (
        <SemesterPlanView
          key={plan.id}
          workspace={workspace}
          plan={plan}
          items={prosemItems[plan.id] || []}
          onMeetingClick={onMeetingClick}
          onAddItem={(step?: number) => onStartPlanning?.(step)}
          onGenerateClick={canAccessAutoGenerate ? async (slot, onProgress) => {
            const item = (prosemItems[plan.id] || []).find(i => i.id === slot.prosem_item_id);
            if (item) {
              const success = await generateWorkspaceMeetingDirect(workspace, item, slot, onProgress);
              if (success) {
                refresh();
              }
            }
          } : undefined}
        />
      ))}

      <ProtaProsemViewerModal 
        isOpen={isViewerOpen} 
        onClose={() => setIsViewerOpen(false)} 
        workspace={workspace} 
      />

      <WorkspaceSettingsModal
        isOpen={isSettingsOpen}
        onClose={() => setIsSettingsOpen(false)}
        workspace={workspace}
        onSuccess={() => {
          refreshWorkspaces();
          refresh();
        }}
      />
      
      <AutoGenerateConfirmModal
        isOpen={isAutoGenerateModalOpen}
        onClose={() => setIsAutoGenerateModalOpen(false)}
        onConfirm={async () => {
          setIsEnqueuing(true);
          await generateWorkspaceModul(workspace, prosemItems);
          setIsEnqueuing(false);
        }}
        missingMeetingsCount={totalMeetings - completedMeetings}
        autogenQuota={autogenQuota}
      />
    </div>
  );
};
