/**
 * Hook orchestrator "Dokumen per Pertemuan V2" (Fase 3 — koreksi).
 *
 * Sekuensial: pertemuan 1 → n, dokumen sesuai urutan kanonik. Hanya dokumen
 * yang dipilih yang diproses. Hasil disimpan langsung ke
 * `GenerationResultV2.pertemuan[n].dokumen` — tidak ada state global per jenis
 * dokumen di jalur V2.
 *
 * Aktif hanya ketika `ENABLE_PERTEMUAN_DOCS_V2 === true`.
 */

import { useCallback, useMemo, useRef, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import type {
  BankSoalData,
  FormData,
  GenerationResultV2,
  JenisDokumenPertemuan,
  PertemuanInput,
  SoalConfig,
} from '@/types/modul';
import { ENABLE_PERTEMUAN_DOCS_V2 } from '@/lib/feature-flags';
import { invokeGenerateWithRetry } from '@/lib/invokeWithRetry';
import { normalizeBankSoalImages } from '@/lib/bank-soal-normalize';
import { fromLegacy, type LegacyGenerationState } from '@/lib/result-adapter';
import {
  BACKEND_TYPE_MAP,
  applyDokumenResult,
  buildContextKey,
  buildGenerateQueue,
  buildPertemuanPayload,
  buildPreviousSummaryForTarget,
  canDeletePertemuan,
  emptyResultV2,
  estimateGenerateCalls,
  getPertemuanById,
  hasGeneratedContent,
  LABEL_DOKUMEN,
  removePertemuanById,
  setDokumenContent,
  setDokumenStatus,
  setModulPreface,
  setPilihanDokumen,
  shouldUsePrefaceFlow,
  syncPertemuanResults,
  updateDokumenPertemuan,
  updateDokumenSection,
  validateDokumenShape,
  validateResponseMetaStrict,
  type DeleteCheckResult,
  type GenerateTask,
  type QueueMode,
} from '@/lib/pertemuan-generation';


export interface PertemuanGenerationProgress {
  current: number;
  total: number;
  message: string;
}

export interface PertemuanGenerationCallbacks {
  /** Update kuota dari response backend (remaining/limit/isTrial). */
  onQuota?: (data: Record<string, unknown>) => void;
  /** Notifikasi sukses/gagal ke UI. */
  onNotify?: (message: string, type: 'success' | 'error') => void;
  /** Response `needApiKey === true`. */
  onNeedApiKey?: () => void;
  /**
   * Dipanggil saat user membatalkan reset konteks: form harus dikembalikan
   * ke snapshot konteks terakhir yang disetujui.
   */
  onRestoreContext?: (snapshot: FormData) => void;
  /**
   * Dipanggil saat response modul V2 mengandung `auto_generated`.
   * Penerima harus mengisi kolom form yang masih kosong (identifikasiMurid,
   * jenisPengetahuan, lintasDisiplinIlmu, kemitraan, dll.) — sama seperti
   * `handleAutoGeneratedFields` di flow V1.
   */
  onAutoFill?: (autoGenerated: Record<string, unknown>) => void;
}


export interface UsePertemuanGenerationOptions {
  formData: FormData;
  /** Seed stabil untuk ID (mis. mapel+kelas+materi). */
  seed: string;
  enabled?: boolean;
  /** Konfigurasi Bank Soal (bukan bagian FormData). */
  soalConfig?: SoalConfig;
  callbacks?: PertemuanGenerationCallbacks;
  /** Override invoke — dipakai test. */
  invoke?: typeof invokeGenerateWithRetry;
}

export const usePertemuanGeneration = ({
  formData,
  seed,
  enabled = ENABLE_PERTEMUAN_DOCS_V2,
  soalConfig,
  callbacks,
  invoke = invokeGenerateWithRetry,
}: UsePertemuanGenerationOptions) => {
  const [result, setResultState] = useState<GenerationResultV2>(emptyResultV2);
  const [isGenerating, setIsGenerating] = useState(false);
  const [progress, setProgress] = useState<PertemuanGenerationProgress | null>(null);
  const [lastError, setLastError] = useState<string | null>(null);
  const [pendingContextKey, setPendingContextKey] = useState<string | null>(null);

  const runningRef = useRef(false);
  const cancelRef = useRef(false);
  /**
   * Epoch state V2. Dinaikkan setiap reset / load history sehingga response
   * yang datang terlambat dari antrean lama tidak pernah ditempel kembali.
   */
  const epochRef = useRef(0);
  /** Sumber kebenaran state terbaru selama antrean async (bukan closure stale). */
  const resultRef = useRef<GenerationResultV2>(result);
  const contextKeyRef = useRef<string | null>(null);
  /** Snapshot form pada konteks terakhir yang disetujui (untuk batal reset). */
  const acceptedFormRef = useRef<FormData | null>(null);

  const formDataRef = useRef<FormData>(formData);
  formDataRef.current = formData;
  const soalConfigRef = useRef<SoalConfig | undefined>(soalConfig);
  soalConfigRef.current = soalConfig;
  const cbRef = useRef<PertemuanGenerationCallbacks | undefined>(callbacks);
  cbRef.current = callbacks;

  /** Satu-satunya jalur penulisan state: ref + state selalu sinkron. */
  const setResult = useCallback(
    (
      updater:
        | GenerationResultV2
        | ((prev: GenerationResultV2) => GenerationResultV2),
    ) => {
      const next =
        typeof updater === 'function'
          ? (updater as (p: GenerationResultV2) => GenerationResultV2)(
              resultRef.current,
            )
          : updater;
      resultRef.current = next;
      setResultState(next);
      return next;
    },
    [],
  );

  /** Hidrasi awal dari state legacy — Modul lama TIDAK diantrekan ulang. */
  const hydrateFromLegacy = useCallback(
    (legacy: LegacyGenerationState) => {
      if (!enabled) return;
      const v2 = fromLegacy(legacy, { seed });
      contextKeyRef.current = buildContextKey(legacy.formData ?? formDataRef.current);
      acceptedFormRef.current = legacy.formData ?? formDataRef.current;
      setResult(
        syncPertemuanResults(v2, legacy.formData?.pertemuan ?? [], { seed }),
      );
    },
    [enabled, seed, setResult],
  );

  /**
   * Selaraskan daftar pertemuan dari form (durasi/tambah/hapus) dan pantau
   * perubahan konteks pembelajaran (mapel/kelas/materi/TP/kurikulum).
   */
  const syncFromForm = useCallback(
    (pertemuan: PertemuanInput[], contextKey?: string) => {
      if (!enabled) return;
      if (contextKey !== undefined && contextKey !== contextKeyRef.current) {
        if (contextKeyRef.current === null) {
          contextKeyRef.current = contextKey;
          acceptedFormRef.current = formDataRef.current;
        } else if (hasGeneratedContent(resultRef.current)) {
          // Butuh konfirmasi user sebelum hasil lama dibuang.
          setPendingContextKey(contextKey);
          return;
        } else {
          contextKeyRef.current = contextKey;
          acceptedFormRef.current = formDataRef.current;
          setResult(emptyResultV2());
        }
      }
      setResult((prev) => syncPertemuanResults(prev, pertemuan, { seed }));
    },
    [enabled, seed, setResult],
  );

  /** User setuju membuang hasil V2 lama karena konteks berubah. */
  const confirmContextReset = useCallback(() => {
    if (pendingContextKey === null) return;
    contextKeyRef.current = pendingContextKey;
    acceptedFormRef.current = formDataRef.current;
    setPendingContextKey(null);
    setResult(
      syncPertemuanResults(
        emptyResultV2(),
        formDataRef.current?.pertemuan ?? [],
        { seed },
      ),
    );
  }, [pendingContextKey, seed, setResult]);

  /**
   * User membatalkan: state V2 tidak berubah sama sekali dan form dikembalikan
   * ke snapshot konteks terakhir yang disetujui.
   */
  const cancelContextReset = useCallback(() => {
    setPendingContextKey(null);
    const snapshot = acceptedFormRef.current;
    if (snapshot) cbRef.current?.onRestoreContext?.(snapshot);
    return snapshot;
  }, []);

  const togglePilihan = useCallback(
    (pertemuanId: string, jenis: JenisDokumenPertemuan, value: boolean) => {
      setResult((prev) => setPilihanDokumen(prev, pertemuanId, jenis, value));
    },
    [setResult],
  );

  /** Editor menulis langsung ke dokumen pertemuan (bukan state legacy). */
  const updateDokumen = useCallback(
    (
      pertemuanId: string,
      jenis: JenisDokumenPertemuan,
      updater: (dokumen: unknown) => unknown,
    ) => {
      setResult((prev) => updateDokumenPertemuan(prev, pertemuanId, jenis, updater));
    },
    [setResult],
  );

  /** Inject dokumen dari DB ke state dan ubah status menjadi ok */
  const injectExternalDocuments = useCallback(
    (pertemuanId: string, docs: Partial<Record<JenisDokumenPertemuan, any>>) => {
      setResult((prev) => {
        let next = prev;
        for (const [jenis, content] of Object.entries(docs)) {
          if (content) {
            // Use setDokumenContent (not updateDokumenPertemuan) so it works even when slot is empty
            next = setDokumenContent(next, pertemuanId, jenis as JenisDokumenPertemuan, content);
            next = setDokumenStatus(next, pertemuanId, jenis as JenisDokumenPertemuan, 'ok');
          }
        }
        return next;
      });
    },
    [setResult],
  );

  /** Edit section (path bertitik) pada dokumen pertemuan. */
  const updateSection = useCallback(
    (
      pertemuanId: string,
      jenis: JenisDokumenPertemuan,
      path: string,
      value: unknown,
    ) => {
      setResult((prev) => updateDokumenSection(prev, pertemuanId, jenis, path, value));
    },
    [setResult],
  );

  /** Cek boleh/perlu konfirmasi sebelum menghapus pertemuan. */
  const checkDeletePertemuan = useCallback(
    (pertemuanId: string): DeleteCheckResult =>
      canDeletePertemuan(resultRef.current, pertemuanId),
    [],
  );

  /** Hapus pertemuan by stable ID (hasil pertemuan lain tidak bergeser). */
  const removePertemuan = useCallback(
    (pertemuanId: string) => {
      setResult((prev) => removePertemuanById(prev, pertemuanId));
    },
    [setResult],
  );



  const estimasiPanggilan = useMemo(
    () => estimateGenerateCalls(result, { mode: 'missing' }),
    [result],
  );

  const runQueue = useCallback(
    async (tasks: GenerateTask[]) => {
      if (!enabled) return;
      if (runningRef.current) return; // cegah double-click / race
      if (tasks.length === 0) return;

      runningRef.current = true;
      cancelRef.current = false;
      const epoch = epochRef.current;
      setIsGenerating(true);
      setLastError(null);

      let done = 0;

      try {
        for (const task of tasks) {
          if (cancelRef.current) break;

          // Selalu snapshot state TERBARU (bukan closure, bukan side effect
          // di dalam state updater).
          const snapshot = resultRef.current;
          const target = getPertemuanById(snapshot, task.pertemuanId);
          // Pertemuan dihapus saat antrean berjalan → jangan kirim request.
          if (!target) continue;

          done += 1;
          setProgress({
            current: done,
            total: tasks.length,
            message: `${LABEL_DOKUMEN[task.jenis]} — Pertemuan ${task.nomor}`,
          });
          setResult((prev) =>
            setDokumenStatus(prev, task.pertemuanId, task.jenis, 'pending'),
          );

          const totalPertemuan = snapshot.pertemuan.length;
          const previousSummary = buildPreviousSummaryForTarget(
            snapshot,
            target.nomor,
            { tujuanPembelajaran: formDataRef.current?.tujuanPembelajaran },
          );
          const usePreface = shouldUsePrefaceFlow(snapshot, task);

          const base = buildPertemuanPayload({
            formData: formDataRef.current,
            pertemuan: target,
            totalPertemuan,
            jenis: task.jenis,
            previousSummary: previousSummary || undefined,
            extra:
              task.jenis === 'soal' && soalConfigRef.current
                ? { config: soalConfigRef.current }
                : undefined,
          });

          const payload = usePreface
            ? {
                type: 'modul',
                data: {
                  ...base.data,
                  pertemuan: [
                    {
                      nomorPertemuan: target.nomor,
                      durasi:
                        target.durasiLabel ?? String(target.durasiMenit),
                    },
                  ],
                },
              }
            : base;

          try {
            const resp = await invoke(payload as unknown as Record<string, unknown>);
            if (epochRef.current !== epoch || cancelRef.current) return;
            const d = (resp?.data ?? {}) as Record<string, unknown>;

            if (d.needApiKey === true) {
              cbRef.current?.onNeedApiKey?.();
              throw new Error(
                'API Key diperlukan. Tambahkan API Key di menu Pengaturan.',
              );
            }
            if (d.error) {
              cbRef.current?.onQuota?.(d);
              throw new Error(String(d.error));
            }
            cbRef.current?.onQuota?.(d);

            const metaCheck = validateResponseMetaStrict(d.meta, {
              id: target.id,
              nomor: target.nomor,
              backendType: payload.type,
            });
            if (!metaCheck.ok) throw new Error(metaCheck.reason ?? 'Meta tidak cocok');

            const raw = d.data as Record<string, unknown> | undefined;
            if (!raw) throw new Error('Response kosong dari server');

            let dokumen: unknown = raw;
            let prefacePatch: Record<string, unknown> | null = null;

            if (task.jenis === 'modul') {
              const list = raw.pertemuan as unknown[] | undefined;
              const inner = (Array.isArray(list) ? list[0] : undefined) ?? raw;
              dokumen = {
                ...(inner as Record<string, unknown>),
                nomorPertemuan: target.nomor,
                durasi: target.durasiLabel ?? String(target.durasiMenit),
              };
              if (usePreface) {
                const { pertemuan: _drop, ...rest } = raw;
                void _drop;
                prefacePatch = rest;
              }
            } else if (task.jenis === 'soal' && soalConfigRef.current) {
              dokumen = normalizeBankSoalImages(
                raw as unknown as BankSoalData,
                soalConfigRef.current,
              );
            }

            const shape = validateDokumenShape(task.jenis, dokumen);
            if (!shape.ok) throw new Error(shape.reason ?? 'Struktur dokumen tidak valid');

            setResult((prev) => {
              let next = prev;
              if (prefacePatch) next = setModulPreface(next, prefacePatch);
              return applyDokumenResult(next, task.pertemuanId, task.jenis, dokumen);
            });
            // Jika preface mengandung auto_generated atau berisi identifikasi_murid → isi kolom form yang kosong.
            if (prefacePatch) {
              const autoGenData = prefacePatch.auto_generated ? prefacePatch.auto_generated : prefacePatch;
              cbRef.current?.onAutoFill?.(autoGenData as Record<string, unknown>);
            }
            cbRef.current?.onNotify?.(
              `${LABEL_DOKUMEN[task.jenis]} Pertemuan ${task.nomor} selesai.`,
              'success',
            );
          } catch (err) {
            if (epochRef.current !== epoch) return;
            const message =
              err instanceof Error ? err.message : 'Gagal generate dokumen';
            const full = `${LABEL_DOKUMEN[task.jenis]} Pertemuan ${task.nomor}: ${message}`;
            setLastError(full);
            cbRef.current?.onNotify?.(full, 'error');
            setResult((prev) =>
              setDokumenStatus(
                prev,
                task.pertemuanId,
                task.jenis,
                'error',
                message,
              ),
            );
            // Partial failure: lanjut ke dokumen berikutnya, hasil sukses tetap.
          }
        }
      } finally {
        runningRef.current = false;
        setIsGenerating(false);
        setProgress(null);
      }
    },
    [enabled, invoke, setResult],
  );

  /** Memasukkan dokumen yang belum ada / gagal ke dalam queue di backend (Cron Job). */
  const enqueueMissingDocuments = useCallback(
    async (workspaceId: string, pertemuanIds?: string[]) => {
      if (!enabled) return false;

      const tasks = buildGenerateQueue(resultRef.current, { mode: 'missing', pertemuanIds });
      if (tasks.length === 0) return false;

      const totalPertemuan = resultRef.current.pertemuan.length;
      
      // Cek apakah workspace INI sudah punya antrean aktif (pending/processing)
      const { data: thisWorkspaceTasks } = await supabase
        .from('generation_queue')
        .select('id')
        .eq('workspace_id', workspaceId)
        .in('status', ['pending', 'processing'])
        .limit(1);

      if (thisWorkspaceTasks && thisWorkspaceTasks.length > 0) {
        cbRef.current?.onNotify?.('Workspace ini sudah memiliki antrean yang sedang berjalan. Harap tunggu hingga selesai.', 'error');
        return false;
      }
      
      // Cek apakah user sudah punya antrean aktif di workspace lain
      const { data: otherActiveTasks, error: checkError } = await supabase
        .from('generation_queue')
        .select('workspace_id')
        .in('status', ['pending', 'processing'])
        .neq('workspace_id', workspaceId)
        .limit(1);

      if (!checkError && otherActiveTasks && otherActiveTasks.length > 0) {
        cbRef.current?.onNotify?.('Anda masih memiliki antrean Auto-Generate yang sedang berjalan di Workspace lain. Harap tunggu hingga selesai atau batalkan.', 'error');
        return false;
      }
      
      const insertData = tasks.map((task) => {
        const target = getPertemuanById(resultRef.current, task.pertemuanId);
        if (!target) return null;
        const previousSummary = buildPreviousSummaryForTarget(resultRef.current, target.nomor, { tujuanPembelajaran: formDataRef.current?.tujuanPembelajaran });
        
        const base = buildPertemuanPayload({
          formData: formDataRef.current,
          pertemuan: target,
          totalPertemuan,
          jenis: task.jenis,
          previousSummary: previousSummary || undefined,
          extra:
            task.jenis === 'soal' && soalConfigRef.current
              ? { config: soalConfigRef.current }
              : undefined,
        });

        const usePreface = shouldUsePrefaceFlow(resultRef.current, task);
        const payload = usePreface
          ? { type: `generate_${task.jenis}_v2_preface`, data: base }
          : { type: `generate_${task.jenis}_v2`, data: base };

        return {
          workspace_id: workspaceId,
          pertemuan_id: task.pertemuanId,
          jenis_dokumen: task.jenis,
          payload: payload,
          status: 'pending'
        };
      }).filter(Boolean);

      if (insertData.length === 0) return false;

      const { error } = await supabase.from('generation_queue').insert(insertData);
      if (error) {
        console.error("Gagal memasukkan ke queue", error);
        cbRef.current?.onNotify?.(`Gagal memasukkan ${insertData.length} dokumen ke antrean`, 'error');
        return false;
      }

      // Tandai workspace sebagai sudah diautogenerate
      await supabase.from('workspaces').update({ is_autogenerated: true }).eq('id', workspaceId);

      cbRef.current?.onNotify?.(`${insertData.length} dokumen berhasil dimasukkan ke antrean background`, 'success');
      return true;
    },
    [enabled]
  );

  /** Generate dokumen yang belum ada / gagal (tidak mengulang yang sudah OK). */
  const generateMissing = useCallback(
    (pertemuanIds?: string[]) =>
      runQueue(
        buildGenerateQueue(resultRef.current, { mode: 'missing', pertemuanIds }),
      ),
    [runQueue],
  );

  /** Regenerate eksplisit (user memilih ulang secara sadar). */
  const regenerate = useCallback(
    (pertemuanIds?: string[], mode: QueueMode = 'all') =>
      runQueue(buildGenerateQueue(resultRef.current, { mode, pertemuanIds })),
    [runQueue],
  );

  const regenerateDokumen = useCallback(
    (pertemuanId: string, jenis: JenisDokumenPertemuan) => {
      const p = getPertemuanById(resultRef.current, pertemuanId);
      if (!p) return;
      if ((p.status[jenis] ?? 'idle') === 'pending') return;
      const task: GenerateTask = {
        pertemuanId,
        nomor: p.nomor,
        jenis,
        backendType: BACKEND_TYPE_MAP[jenis],
      };
      return runQueue([task]);
    },
    [runQueue],
  );

  const cancel = useCallback(() => {
    cancelRef.current = true;
  }, []);

  /**
   * Reset lifecycle V2: batalkan antrean, buang seluruh dokumen/status/error,
   * dan naikkan epoch supaya response yang telat tidak ditempel kembali.
   * Skeleton pertemuan tetap disinkronkan dari form agar UI V2 tidak hilang.
   */
  const resetV2 = useCallback(() => {
    cancelRef.current = true;
    epochRef.current += 1;
    setPendingContextKey(null);
    setLastError(null);
    setProgress(null);
    contextKeyRef.current = buildContextKey(formDataRef.current);
    acceptedFormRef.current = formDataRef.current;
    setResult(
      syncPertemuanResults(emptyResultV2(), formDataRef.current?.pertemuan ?? [], {
        seed,
      }),
    );
  }, [seed, setResult]);

  /**
   * Muat hasil V2 dari history. Tidak melakukan generate apa pun; state lama
   * dibuang total lebih dulu sehingga dokumen history A tidak tercampur B.
   */
  const loadResult = useCallback(
    (next: GenerationResultV2, nextForm?: FormData) => {
      cancelRef.current = true;
      epochRef.current += 1;
      setPendingContextKey(null);
      setLastError(null);
      setProgress(null);
      const form = nextForm ?? formDataRef.current;
      contextKeyRef.current = buildContextKey(form);
      acceptedFormRef.current = form;
      setResult({ ...emptyResultV2(), ...next, version: 2 });
    },
    [setResult],
  );

  return {
    enabled,
    result,
    setResult,
    syncFromForm,
    hydrateFromLegacy,
    pendingContextKey,
    confirmContextReset,
    cancelContextReset,
    togglePilihan,
    updateDokumen,
    updateSection,
    injectExternalDocuments,
    checkDeletePertemuan,
    removePertemuan,

    estimasiPanggilan,
    isGenerating,
    progress,
    lastError,
    generateMissing,
    enqueueMissingDocuments,
    regenerate,
    regenerateDokumen,
    cancel,
    resetV2,
    loadResult,
  };
};
