ALTER TABLE public.workspaces ADD COLUMN IF NOT EXISTS is_autogenerated BOOLEAN NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS idx_workspaces_is_autogenerated ON public.workspaces(user_id, is_autogenerated) WHERE is_autogenerated = true;
